### ISSUE TITLE
(Question) Change the value of a default variable of the env using make_vec_env

### ISSUE THREAD

**Issue by Chaivara** [hill-a/stable-baselines#1051] opened 2020-12-01 09:07 UTC
(Question) I'm using make_vec_env to create parallel workers. I want to change a variable value from default one. Tried 2 approaches

1. env.configure() throws errors. 
2. I dont know how to use Kwargs in make_vec_env() 
There should be a better way of doing this. Any help would be appreciated.

**Code example**
```
import highway_env
from stable_baselines.common import make_vec_env

env = make_vec_env('highway-v0')
env.envs[0].env.configure({"observation": {"type": "Kinematics","vehicles_count": 15}})
env.envs[0].env.reset()
env.reset()

```

**System Info**
Describe the characteristic of your environment:
 * stable-baselines was installed using pip - version 2.10.1
 * GPU is being used
 * Python version 3.7
 * Tensorflow version 1.15
 * highway-env [https://github.com/eleurent/highway-env](url)

```
Traceback (most recent call last):
  File "W:/CMV/pythonProject-gpu/New.py", line 46, in <module>
    env.reset()
  File "W:\CMV\anaconda3\envs\tf-gpu\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "W:\CMV\anaconda3\envs\tf-gpu\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (15,5) into shape (5,5)

```

**Comment by araffin** [comment] 2020-12-01 09:18
Probably a duplicate of https://github.com/hill-a/stable-baselines/issues/1032
and you should take a look at `env_method()` method (cf doc).

**Closed** 2021-02-01 16:48 UTC
Labels: RTFM, duplicate, question
