### ISSUE TITLE
ValueError: could not broadcast input array from shape (2) into shape (7,3,5)

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#242] opened 2019-03-24 07:39 UTC
**Describe the bug**
I am trying to run stable_baseline alogs such as ppo1, ddpg and get this error:
ValueError: could not broadcast input array from shape (2) into shape (7,1,5)

**Code example**
# action will be the portfolio weights from 0 to 1 for each asset
        self.action_space = gym.spaces.Box(-1, 1, shape=(len(instruments) + 1,), dtype=np.float32)  # include cash

        # get the observation space from the data min and max
        self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(instruments), window_length, history.shape[-1]), dtype=np.float32)

I tried using obs.reshape(-1), obs.flatten(), obs.ravel() nothing works. Also tried CnnPolicy onstead of MlpPolicy and got:

ValueError: Negative dimension size caused by subtracting 8 from 7 for 'model/c1/Conv2D' (op: 'Conv2D') with input shapes: [?,7,1,5], [8,8,5,32].

**System Info**
Describe the characteristic of your environment:
 *library was installed using:
git clone https://github.com/hill-a/stable-baselines.git
cd stable-baselines
pip install -e .
 * GPU models and configuration: no gpu, cpu only
 * Python 3.7.2
 * tensorflow  1.12.0
 * stable-baselines   2.4.1

**Additional context**

tensorflow==1.13.1 cpu

**Comment by araffin** [comment] 2019-03-24 09:24
Hello again,

as written in the previous topic:

>A simple solution consists in reshaping your observation to a 1D vector, so you can use MlpPolicy on it.
Otherwise, if you want to keep your observation with that exact shape, then you have to define a custom policy, as the default CnnPolicy was made for images (of shape 64x64xn) and normalization (dividing by 255.) is automatically applied in this case.

>Again, do not forget to add more context for your problem next time by filling COMPLETELY the issue template ;)

**Comment by hn2** [comment] 2019-03-24 10:44
Thanks.

I tried reshaping the observation (in both step and reset methods) as obs = obs.reshape(-1)

Is this the correct way?

Still getting 

ValueError: could not broadcast input array from shape (2) into shape (7,1,5)

**Comment by hn2** [comment] 2019-03-24 20:38
Still not able to solve this.

 

I tried to use the flatten() method to return flattened observations (return obs.flatten(), info)

I still get:

 

model.learn(total_timesteps=10000)

  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/ppo1/pposgd_simple.py", line 230, in learn

    seg = seg_gen.__next__()

  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/trpo_mpi/utils.py", line 35, in traj_segment_generator

    observation = env.reset()

  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 523, in reset

    return self.venv.reset()[0]

  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 57, in reset

    self._save_obs(env_idx, obs)

  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 75, in _save_obs

    self.buf_obs[key][env_idx] = obs

ValueError: could not broadcast input array from shape (2) into shape (7,1,5)

**Comment by hn2** [comment] 2019-03-26 08:18
I tried CnnPolicy instead of MlpPolicy and got this error:
ValueError: Negative dimension size caused by subtracting 8 from 7 for 'model/c1/Conv2D' (op: 'Conv2D') with input shapes: [?,7,1,5], [8,8,5,32].

**Comment by araffin** [comment] 2019-03-26 17:30
For the fourth and last time, please fill in the  issue template COMPLETELY otherwise we cannot help you, and i will have to close this issue.

**Comment by araffin** [comment] 2019-03-26 19:22
Hello,
the problem comes from your observation space, you should define it properly so it is consistent with the observation of your environment.
Current, your observation space has a shape of dimension 3 but your are giving a 1D vector to the agent.

**Comment by hn2** [comment] 2019-03-26 19:55
It is consistent. It should be 3d: first dimension is the list of assets, second dimension are historical prices (defined by window_length = 1..50, third dimension is open, high, low, close, volume. Where do you see that I am feeding the agent with 1D vector?

**Comment by araffin** [comment] 2019-03-26 20:11
>It is consistent. It should be 3d: first dimension is the list of assets, second dimension are historical prices (defined by window_length = 1..50, third dimension is open, high, low, close, volume. Where do you see that I am feeding the agent with 1D vector?

sooner in the discussion...
>A simple solution consists in reshaping your observation to a 1D vector, so you can use MlpPolicy on it.

**Comment by hn2** [comment] 2019-03-26 20:20
As said before, I tried that but it didn't work (with reshape, flatten, ravel).

**Comment by hill-a** [comment] 2019-03-27 17:55
>  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 523, in reset 
>
>     return self.venv.reset()[0] 
>
> File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 57, in reset 
>
>     self._save_obs(env_idx, obs) 
>
> File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 75, in _save_obs 
>
>     self.buf_obs[key][env_idx] = obs 
>
> ValueError: could not broadcast input array from shape (2) into shape (7,1,5) 

This is a Numpy error, cause by `buf_obs` being `shape=(7, 1, 5)`, which makes sense since you told it `shape=(len(instruments), window_length, history.shape[-1])`. As @araffin said, you cannot have a n-dimensional vector, except for n==1 or (n==3 AND shape[0:2] >= 64 AND shape[2] == 3 or 1). Here you have a 3 dimensional vector with 7, 1 and 5 as it's width, heigh and depth, which will not work for CNN.

The solution as such is to drop to a one dimensional vector: 
```python
self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(instruments) * window_length * history.shape[-1],), dtype=np.float32)
```
NOTE the multiplication in `shape=(len(instruments) * window_length * history.shape[-1],)` and not commas, this gives you `shape=(35,)`, which is now compatible with MlpPolicy, and now you can use `obs.reshape(-1)` in your `step()` AND `reset()` functions.

If you need more help, we are going to need you entire environment code, as I am incapable of deducing Numpy broadcasting errors without knowing how the numpy array was formed AND how it was used.

**Comment by hn2** [comment] 2019-03-27 19:36
Ok I changed is as suggested I now get:
  model.learn(total_timesteps=10000)
  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/ppo1/pposgd_simple.py", line 230, in learn
    seg = seg_gen.__next__()
  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/trpo_mpi/utils.py", line 35, in traj_segment_generator
    observation = env.reset()
  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 523, in reset
    return self.venv.reset()[0]
  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 57, in reset
    self._save_obs(env_idx, obs)
  File "/home/ubuntu/anaconda2/lib/python3.6/site-packages/stable_baselines/common/vec_env/dummy_vec_env.py", line 75, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: cannot copy sequence with size 2 to array axis with dimension 35

**Comment by hill-a** [comment] 2019-03-27 21:00
> If you need more help, we are going to need you entire environment code, as I am incapable of deducing Numpy broadcasting errors without knowing how the numpy array was formed AND how it was used.

I have no idea what your environment is sending down to the DummyVecEnv, as such I'm not capable of helping you without the original code, for me you are simply sending the wrong information in `reset()` and I am clueless to why without further information.

Other than that, this does not seem like a stable baselines issues, rather an implementation issue, make sure you followed the guide for custom environment [https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html](https://stable-baselines.readthedocs.io/en/master/guide/custom_env.html) and that your `reset()` implementation is correctly returning the observation.

**Comment by araffin** [comment] 2019-03-27 22:09
I agree with @hill-a , this is apparently not an error due to stable-baselines but to a custom environment. I think we gave you already enough information to help you debug your environment.

We do not do personal debugging and focus on SB issues, so I will close this one.

**Closed by araffin** 2019-03-27 22:09 UTC
Labels: custom gym env

**Comment by araffin** [comment] 2019-03-27 22:14
Related issue: https://github.com/hill-a/stable-baselines/issues/88

**Comment by hn2** [comment] 2019-03-27 22:57
It looks like it did flattened the array as it now has dimension 35
I just did exactly what you said and changed the observation space

**Comment by araffin** [comment] 2019-03-27 23:03
You may have the same issue as here: https://github.com/hill-a/stable-baselines/issues/214

**Comment by hn2** [comment] 2019-03-27 23:22
Here is the entire code my custom env:

class PortfolioEnv(gym.Env):
	
	metadata = {'render.modes': ['human', 'ansi']}

	def __init__(self,
				 history,
				 instruments,
				 capital_base=1e6,
				 steps=504,  # default 2 years
				 trading_cost=0.0025,
				 time_cost=0.0025,
				 window_length=1,
				 start_idx=0,
				 sample_start_date=None
				 ):
	
		self.history = history
		self.instruments = instruments
		self.capital_base = capital_base
		self.steps = steps # + 1
		self.current_step = 0
		self.trading_cost = trading_cost
		self.time_cost = time_cost
		self.window_length = window_length
		self.start_idx = start_idx
		self.current_idx = 0
		self.start_date = sample_start_date

		assert history.shape[0] == len(instruments), 'Number of stock is not consistent'

		self.cost = trading_cost
		self.time_cost = time_cost
		self.old_portfolio_value = self.capital_base
		self.new_portfolio_value = self.capital_base

		self.done = self.new_portfolio_value <= 0 or self.current_step >= self.steps
		self.infos = []

		# openai gym attributes
		# action will be the portfolio weights from -1 to 1 for each instrument
		self.action_space = gym.spaces.Box(-1, 1, shape=(len(instruments) + 1,), dtype=np.float32)  # include cash

		# get the observation space from the data min and max
		self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(instruments) * window_length * history.shape[-1],), dtype=np.float32)

	def step(self, action):
		"""
		Step the env.
		Actions should be portfolio [w0...]
		- Where wn is a portfolio weight from 0 to 1. The first is cash_bias
		- cn is the portfolio conversion weights see PortioSim._step for description
		"""
		np.testing.assert_almost_equal(action.shape, (len(self.instruments) + 1,))

		# normalise just in case
		action = np.clip(action, -1, 1)

		weights = action  # np.array([cash_bias] + list(action))  # [w0, w1...]
		weights /= (np.sum(np.abs(weights)) + eps)
		weights[0] += np.clip(1 - np.sum(np.abs(weights)), 0, 1)  # so if weights are all zeros we normalise to [1,0...]

		assert ((action >= -1) * (action <= 1)).all(), 'all action values should be between -1 and 1. Not %s' % action
		np.testing.assert_almost_equal(np.sum(np.abs(weights)), 1.0, 3, err_msg='absolute weights should sum to 1. action="%s"' % weights)

		self.current_step += 1
		obs = self.history[:, self.current_step:self.current_step + self.window_length, :].copy()
		# normalize obs with open price

		# used for compute optimal action and sanity check
		ground_truth_obs = self.history[:, self.current_step + self.window_length:self.current_step + self.window_length + 1, :].copy()

		# concatenate observation with ones (case observation)
		cash_obs = np.ones((1, self.window_length, obs.shape[2]))
		obs = np.concatenate((cash_obs, obs), axis=0)
		cash_ground_truth = np.ones((1, 1, ground_truth_obs.shape[2]))
		ground_truth_obs = np.concatenate((cash_ground_truth, ground_truth_obs), axis=0)

		# relative price vector of last observation (close/open)
		open_price_vector = obs[:, -1, 0]
		close_price_vector = obs[:, -1, 3]
		return_vector = close_price_vector / open_price_vector

		"""
		Step.
		weights - new action of portfolio weights - e.g. [0.1,0.9,0.0]
		return_vector - price relative vector also called return e.g. [1.0, 0.9, 1.1]
		Numbered equations are from https://arxiv.org/abs/1706.10059
		"""
		#   assert w1.shape == y1.shape, 'w1 and y1 must have the same shape'
		assert return_vector[0] == 1.0, 'return_vector[0] must be 1 (cash)'

		new_weights = (return_vector * weights) / (np.dot(return_vector, weights) + eps)  # (eq7) weights evolve into new weights at the end of the step due to price change
		total_trx_cost = self.cost * (np.abs(new_weights - weights)).sum()  # (eq16) cost to change portfolio
		assert total_trx_cost < 1.0, 'Cost is larger than current holding'
		self.new_portfolio_value = self.old_portfolio_value * (1 - total_trx_cost) * np.dot(return_vector, weights)  # (eq11) final portfolio value
		self.new_portfolio_value = self.new_portfolio_value * (1 - self.time_cost)  # cost of holding
		rate_of_return = self.new_portfolio_value / self.old_portfolio_value - 1  # rate of returns
		log_rate_of_return = np.log((self.new_portfolio_value + eps) / (self.old_portfolio_value + eps))  # log rate of return
		reward = log_rate_of_return / self.steps * 1000.  # (22) average logarithmic accumulated return
		# remember for next step
		self.old_portfolio_value = self.new_portfolio_value

		info = {
			"reward": reward,
			"portfolio_value": self.new_portfolio_value,
			"return": return_vector.mean(),
			"rate_of_return": rate_of_return,
			"log_return": log_rate_of_return,
			"weights_mean": weights.mean(),
			"weights_std": weights.std(),
			"transaction_cost": total_trx_cost,
		}
		self.infos.append(info)

		# calculate return for buy and hold a bit of each asset
		info['market_value'] = np.cumprod([inf["return"] for inf in self.infos + [info]])[-1]
		self.infos.append(info)

		# add dates
		"""
		info['date'] = index_to_date(self.start_idx + self.src.idx + self.current_step)
		info['steps'] = self.current_step
		info['next_obs'] = ground_truth_obs
		self.infos.append(info)
		"""

		return obs.reshape(-1), reward, self.done, info

	def reset(self):
		self.infos = []
		self.old_portfolio_value = self.capital_base
		self.new_portfolio_value = self.capital_base
		self.current_step = 0

		# get data for this episode, each episode might be different.
		if self.start_date is None:
			self.idx = np.random.randint(low=self.window_length, high=self.history.shape[1] - self.steps)
		else:
			# compute index corresponding to start_date for repeatable sequence
			self.idx = date_to_index(self.start_date) - self.start_idx
			assert self.idx >= self.window_length and self.idx <= self.history.shape[1] - self.steps, \
				'Invalid start date, must be window_length day after start date and simulation steps day before end date'
		# print('Start date: {}'.format(index_to_date(self.idx)))
		data = self.history[:, self.idx - self.window_length:self.idx + self.steps + 1, :4]
		# apply augmentation?
		obs = data[:, self.current_step:self.current_step+ self.window_length, :].copy()
		ground_truth_obs = data[:, self.current_step+ self.window_length:self.current_step+ self.window_length + 1, :].copy()

		cash_obs = np.ones((1, self.window_length, obs.shape[2]))
		obs = np.concatenate((cash_obs, obs), axis=0)
		cash_ground_truth = np.ones((1, 1, ground_truth_obs.shape[2]))
		ground_truth_obs = np.concatenate((cash_ground_truth, ground_truth_obs), axis=0)
		info = {}
		info['next_obs'] = ground_truth_obs
		return obs.reshape(-1), info

	def render(self, mode='human', close=False):
		if close:
			return
		if mode == 'ansi':
			pprint(self.infos[-1])
		elif mode == 'human':
			self.plot()

	def plot(self):
		df_info = pd.DataFrame(self.infos)
		df_info['date'] = pd.to_datetime(df_info['date'], format='%Y-%m-%d')
		df_info.set_index('date', inplace=True)
		mdd = max_drawdown(df_info.rate_of_return + 1)
		sharpe_ratio = sharpe(df_info.rate_of_return)
		title = 'max_drawdown={: 2.2%} sharpe_ratio={: 2.4f}'.format(mdd, sharpe_ratio)
		df_info[["portfolio_value", "market_value"]].plot(title=title, fig=plt.gcf(), rot=30)

**Comment by araffin** [comment] 2019-03-27 23:33
you are returning a tuple in the reset method. It should be only an observation, @hill-a was right.

**Comment by hn2** [comment] 2019-03-28 00:07
What do I need to change in this code?

**Comment by hn2** [comment] 2019-03-28 21:13
What do you mean by only observation?

**Comment by hn2** [comment] 2019-03-29 00:00
I finally succeeded in running the model. Do you have documentation how to interpret the output?
(verbosity=1)
********** Iteration 0 ************
Optimizing...
     pol_surr |    pol_entpen |       vf_loss |            kl |           ent
      0.00148 |      -0.11349 |       0.03412 |       0.01007 |      11.34949
     -0.01255 |      -0.11346 |       0.02966 |       0.02644 |      11.34579
     -0.02320 |      -0.11343 |       0.02311 |       0.02290 |      11.34317
     -0.02648 |      -0.11338 |       0.01937 |       0.01414 |      11.33826
Evaluating losses...
     -0.03064 |      -0.11335 |       0.01735 |       0.01275 |      11.33532
----------------------------------
| EpThisIter      | 0            |
| EpisodesSoFar   | 0            |
| TimeElapsed     | 15.9         |
| TimestepsSoFar  | 256          |
| ev_tdlam_before | -3.03        |
| loss_ent        | 11.335321    |
| loss_kl         | 0.01274954   |
| loss_pol_entpen | -0.113353215 |
| loss_pol_surr   | -0.030639375 |
| loss_vf_loss    | 0.017349362  |
----------------------------------
********** Iteration 1 ************
Optimizing...
     pol_surr |    pol_entpen |       vf_loss |            kl |           ent
      0.00121 |      -0.11333 |       0.02765 |       0.00017 |      11.33332
     -0.00925 |      -0.11329 |       0.02208 |       0.00160 |      11.32853
     -0.01676 |      -0.11323 |       0.02083 |       0.00704 |      11.32298
     -0.02069 |      -0.11318 |       0.01745 |       0.01167 |      11.31769
Evaluating losses...
     -0.02851 |      -0.11316 |       0.01342 |       0.01097 |      11.31555
----------------------------------
| EpThisIter      | 0            |
| EpisodesSoFar   | 0            |
| TimeElapsed     | 20.9         |
| TimestepsSoFar  | 512          |
| ev_tdlam_before | -17.4        |
| loss_ent        | 11.315554    |
| loss_kl         | 0.010965543  |
| loss_pol_entpen | -0.11315554  |
| loss_pol_surr   | -0.028507909 |
| loss_vf_loss    | 0.013420929  |
----------------------------------

**Comment by hill-a** [comment] 2019-03-29 13:05
There is no coordination between the logging for the methods unfortunatly. I'm guessing from the losses in the log that you are using PPO1 here, so here are the descriptions:

- **EpThisIter**: _number of episodes that occured during this iteration_
- **EpisodesSoFar**: _number of episodes that occured so far_
- **TimeElapsed**: _the elapsed time in seconds_
- **TimestepsSoFar**: _the number of timesteps so far_
- **ev_tdlam_before**: _explained variance between predicted value function and TD(lambda) estimator_
- **loss_ent**: _entropy loss_
- **loss_kl**: _Kullback-Leibler loss_
- **loss_pol_entpen**: _entropy loss times -entropy coef_
- **loss_pol_surr**: _pessimistic surrogate loss_
- **loss_vf_loss**: _value function loss_

**Comment by hn2** [comment] 2019-03-29 17:37
I am using the tensorboard integration. Is it possible to print additional info returning from the step on the tensorboard web page?

**Comment by hn2** [comment] 2019-03-29 19:14
Also, I am trying to test ddpg. I get:
the action space low and high must be symmetric.
There is an assertion in your ddpg code, however my action space is not symmetrical at this point:
self.action_space = gym.spaces.Box(0, 1, shape=(len(self.src.asset_names) + 1,), dtype=np.float32)

**Comment by hn2** [comment] 2019-03-29 19:45
When I changed to:

self.action_space = gym.spaces.Box(-1., 1., shape=(len(self.src.asset_names) + 1,), dtype=np.float32)  
self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(self.src.asset_names) + 1, window_length, history.shape[-1],), dtype=np.float32)

and I do:

def step(self, action):

        print(action)

I always get: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan ..

It is a problem with my env or with the agent?

**Comment by hn2** [comment] 2019-03-31 12:46
Another error that I get on windows when trying to import stable_baseline:
Exception has occurred: AssertionError
expected file or str, got <_pydevd_bundle.pydevd_io.IORedirector object at 0x000001EE6A3464E0>

in logger.py line 56:
 assert hasattr(filename_or_file, 'read'), 'expected file or str, got %s' % filename_or_file
The same code works on ubuntu. I guess that something is wring with my windows python environment but what?

**Comment by hill-a** [comment] 2019-04-01 09:06
> I am using the tensorboard integration. Is it possible to print additional info returning from the step on the tensorboard web page?

No, that would be quite difficult to do. It would be better to use the validation part of the [**example code given in the doc**](https://stable-baselines.readthedocs.io/en/master/guide/quickstart.html#getting-started):
```python
obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    print(info)
    env.render()
```

> When I changed to:
>
>     self.action_space = gym.spaces.Box(-1., 1., shape=(len(self.src.asset_names) + 1,), dtype=np.float32)
>     self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(self.src.asset_names) + 1, window_length, history.shape[-1],), dtype=np.float32)
>
> and I do:
>
>     def step(self, action):
>        print(action)
>
> I always get: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan ..
> 
> It is a problem with my env or with the agent?

As discussed earlier, this will not work, observation space needs to be one dimensional:
```python
self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(len(instruments) * window_length * history.shape[-1],), dtype=np.float32)
```

> Another error that I get on windows when trying to import stable_baseline:
>
>     Exception has occurred: AssertionError
>         expected file or str, got <_pydevd_bundle.pydevd_io.IORedirector object at 0x000001EE6A3464E0>
>     in logger.py line 56:
>         assert hasattr(filename_or_file, 'read'), 'expected file or str, got %s' % filename_or_file
>
> The same code works on ubuntu. I guess that something is wring with my windows python environment but what?

Next time, tell me what you are using, it helps avoid guessing. So, I'm assuming you are using Pycharm, since it is a `_pydevd_bundle` object. 
This error is caused by the logger taking stdout and asserting it is a string or not a readable IO object. Here with pycharm under windows it seems to be the case. 
I quick fix for this would be to comment that assertation line 56 in logger.py

**Comment by hn2** [comment] 2019-04-01 09:12
I am using VS code.

**Comment by hill-a** [comment] 2019-04-01 09:30
> I am using VS code.

Ok, [this](https://github.com/Microsoft/ptvsd/blob/6d2062bb37083cd7d45b044af2d381be934e2f0d/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_io.py#L7) is what stable-baselines is crashing on, it seems that for some reason the object does not have a read attribute, not sure why though as this code should work and dates from the [initial commit of VS](https://github.com/Microsoft/ptvsd/blame/5ac67eb59476523536ebae789c69fce9c3d86f52/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_io.py#L26)... Again, comment that assertation line 56 in logger.py. it is only there as a safeguard for those who are playing with the logger, which I am assuming you are not.

**Comment by hn2** [comment] 2019-04-01 11:41
What is the solution then? move to another ide?

**Comment by hill-a** [comment] 2019-04-01 11:45
For the last time
> Again, comment that assertation line 56 in logger.py

In stable-baselines/commons folder there is the file logger.py, comment line 56. 
Will do a hotfix later. Locking thread as we do not do tech support.
