### ISSUE TITLE
How to directly rebuild the model from saved zip file? 

### ISSUE THREAD

**Issue by QuXinghuaNTU** [hill-a/stable-baselines#735] opened 2020-03-10 11:12 UTC
Currently I want to rebuild the stable baseline model in keras and pytorch. It seems that the model cannot directly save to a h5 file. Thus I want to rebuild from the zip file save in this code.
```python
log_dir = "test_save/"
model_dqn.save(log_dir + "pong")
```
This file contains the model structure in``` parameter_list```, and weights in``` parameters```. However, I cannot rebuild the model from these two files with the code below:
```from keras.models import model_from_json
# load json and create model
json_file = open('parameter_list', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

loaded_model.load_weights("parameters")
```

**Comment by QuXinghuaNTU** [comment] 2020-03-10 11:13
The error is:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-fac515a3d275> in <module>
      4 loaded_model_json = json_file.read()
      5 json_file.close()
----> 6 loaded_model = model_from_json(loaded_model_json)
      7 
      8 loaded_model.load_weights("parameters")

~/anaconda3/envs/distillation/lib/python3.7/site-packages/keras/engine/saving.py in model_from_json(json_string, custom_objects)
    490     config = json.loads(json_string)
    491     from ..layers import deserialize
--> 492     return deserialize(config, custom_objects=custom_objects)
    493 
    494 

~/anaconda3/envs/distillation/lib/python3.7/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~/anaconda3/envs/distillation/lib/python3.7/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    167     else:
    168         raise ValueError('Could not interpret serialized ' +
--> 169                          printable_module_name + ': ' + identifier)
    170 
    171 

TypeError: can only concatenate str (not "list") to str`

**Comment by araffin** [comment] 2020-03-10 11:53
Seems like a duplicate of #699

**Comment by Miffyli** [comment] 2020-03-10 12:39
Just to add here: The model files do not store the architecture of the network (this is only available as a pickled Python function, which creates a TF graph). You have to manually build a corresponding network, load the `parameters` from the file and assign them correctly.

Note to self: For v3, I should look into a possible common format for saving the model architecture as well, if in any way possible (in a convenient way).

**Comment by araffin** [comment] 2020-03-10 13:58
>Note to self: For v3, I should look into a possible common format for saving the model architecture as well, if in any way possible (in a convenient way).

ONNX export ? or tracing using pytorch jit?

**Comment by QuXinghuaNTU** [comment] 2020-03-11 00:25
> Just to add here: The model files do not store the architecture of the network (this is only available as a pickled Python function, which creates a TF graph). You have to manually build a corresponding network, load the `parameters` from the file and assign them correctly.
> 
> Note to self: For v3, I should look into a possible common format for saving the model architecture as well, if in any way possible (in a convenient way).

Thanks, Maffyli. I tried to build a model in Keras and load weights for this model. However, it still did not work. Could you please kindly have a brief look at the error and share your expert opinion?
The code is below:
`from keras import optimizers
from keras import backend as K
from keras.losses import kullback_leibler_divergence,mean_squared_error
from keras.callbacks import ReduceLROnPlateau, EarlyStopping
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout, Activation, BatchNormalization
method = 'dqn'
game   = 'Pong'
with open("trained_agents/{}/{}NoFrameskip-v4.pkl".format(method,game), 'rb') as file:
    pickle_model = pickle.load(file)
weights = pickle_model[-1]

model1 = Sequential()
model1.add(Conv2D(32, (8, 8), strides=(4, 4), input_shape=(84, 84, 4)))
model1.add(Activation('relu'))
model1.add(Conv2D(64, (4, 4), strides=(2, 2)))
model1.add(Activation('relu'))
model1.add(Conv2D(64, (3, 3), strides=(1, 1)))
model1.add(Activation('relu'))
model1.add(Flatten())
model1.add(Dense(512))
model1.add(Activation('relu'))
model1.add(Dense(6))

model1.set_weights(weights)`

**Comment by QuXinghuaNTU** [comment] 2020-03-11 00:35
Another way would be: extracting the dqn model from the build TF graph and save it independently. I did not check whether it is possible. In that case, we may need to change the source code a lot.

**Comment by Miffyli** [comment] 2020-03-11 09:37
Please take a look at the [documentation on exporting models](https://stable-baselines.readthedocs.io/en/master/guide/export.html#manual-export). You have to get the parameters as numpy arrays with `get_parameters`, and map these to correct Keras layers. I had a mapping like this for **Keras model to stable-baselines**. The key tells stable-baselines parameter name, and value is a lambda function that retrieves corresponding layer from a Keras model.

```python
# Mapping from stable-baselines agent variable
# name to a function that takes in keras model
# and assigns right variables
CNN_PARAMS = {
    "model/cnn1/w:0": lambda model: model.get_layer("conv2d_1").get_weights()[0],
    "model/cnn1/b:0": lambda model: model.get_layer("conv2d_1").get_weights()[1][None, :, None, None],
    "model/cnn2/w:0": lambda model: model.get_layer("conv2d_2").get_weights()[0],
    "model/cnn2/b:0": lambda model: model.get_layer("conv2d_2").get_weights()[1][None, :, None, None],
    "model/cnn3/w:0": lambda model: model.get_layer("conv2d_3").get_weights()[0],
    "model/cnn3/b:0": lambda model: model.get_layer("conv2d_3").get_weights()[1][None, :, None, None],
    "model/cnn_fc1/w:0": lambda model: model.get_layer("dense_1").get_weights()[0],
    "model/cnn_fc1/b:0": lambda model: model.get_layer("dense_1").get_weights()[1]
}
```

>Another way would be: extracting the dqn model from the build TF graph and save it independently.

This is planned for v3 with PyTorch backend.

**Comment by QuXinghuaNTU** [comment] 2020-03-12 01:29
> Please take a look at the [documentation on exporting models](https://stable-baselines.readthedocs.io/en/master/guide/export.html#manual-export). You have to get the parameters as numpy arrays with `get_parameters`, and map these to correct Keras layers. I had a mapping like this for **Keras model to stable-baselines**. The key tells stable-baselines parameter name, and value is a lambda function that retrieves corresponding layer from a Keras model.
> 
> ```python
> # Mapping from stable-baselines agent variable
> # name to a function that takes in keras model
> # and assigns right variables
> CNN_PARAMS = {
>     "model/cnn1/w:0": lambda model: model.get_layer("conv2d_1").get_weights()[0],
>     "model/cnn1/b:0": lambda model: model.get_layer("conv2d_1").get_weights()[1][None, :, None, None],
>     "model/cnn2/w:0": lambda model: model.get_layer("conv2d_2").get_weights()[0],
>     "model/cnn2/b:0": lambda model: model.get_layer("conv2d_2").get_weights()[1][None, :, None, None],
>     "model/cnn3/w:0": lambda model: model.get_layer("conv2d_3").get_weights()[0],
>     "model/cnn3/b:0": lambda model: model.get_layer("conv2d_3").get_weights()[1][None, :, None, None],
>     "model/cnn_fc1/w:0": lambda model: model.get_layer("dense_1").get_weights()[0],
>     "model/cnn_fc1/b:0": lambda model: model.get_layer("dense_1").get_weights()[1]
> }
> ```
> 
> > Another way would be: extracting the dqn model from the build TF graph and save it independently.
> 
> This is planned for v3 with PyTorch backend.

Thanks for your reply. This mapping looks like ignore the last fully connected layer (i.e., from 512 hidden nodes to the action outputs). It would be soooo nice if you can share one example for loading from pkl file and then converting weights to a keras model. In that way, I think people can also save models to other formats (e.g., .h5 that is mentioned by ChunJyeBehBeh). However, this is based on your team has such an extension plan. Thanks so much for your help anyway:)

**Comment by QuXinghuaNTU** [comment] 2020-03-12 09:26
> Please take a look at the [documentation on exporting models](https://stable-baselines.readthedocs.io/en/master/guide/export.html#manual-export). You have to get the parameters as numpy arrays with `get_parameters`, and map these to correct Keras layers. I had a mapping like this for **Keras model to stable-baselines**. The key tells stable-baselines parameter name, and value is a lambda function that retrieves corresponding layer from a Keras model.
> 
> ```python
> # Mapping from stable-baselines agent variable
> # name to a function that takes in keras model
> # and assigns right variables
> CNN_PARAMS = {
>     "model/cnn1/w:0": lambda model: model.get_layer("conv2d_1").get_weights()[0],
>     "model/cnn1/b:0": lambda model: model.get_layer("conv2d_1").get_weights()[1][None, :, None, None],
>     "model/cnn2/w:0": lambda model: model.get_layer("conv2d_2").get_weights()[0],
>     "model/cnn2/b:0": lambda model: model.get_layer("conv2d_2").get_weights()[1][None, :, None, None],
>     "model/cnn3/w:0": lambda model: model.get_layer("conv2d_3").get_weights()[0],
>     "model/cnn3/b:0": lambda model: model.get_layer("conv2d_3").get_weights()[1][None, :, None, None],
>     "model/cnn_fc1/w:0": lambda model: model.get_layer("dense_1").get_weights()[0],
>     "model/cnn_fc1/b:0": lambda model: model.get_layer("dense_1").get_weights()[1]
> }
> ```
> 
> > Another way would be: extracting the dqn model from the build TF graph and save it independently.
> 
> This is planned for v3 with PyTorch backend.

Hi Miffyli, I have built a keras model and load the weights from the pkl file. The code for doing so is shown as:
```
## Load the existing pkl models (trained by stable baselines)
import pickle
method = 'dqn'
game   = 'Pong'
with open("trained_agents/{}/{}NoFrameskip-v4.pkl".format(method,game), 'rb') as file:
    pickle_model = pickle.load(file)
pkl_weights = pickle_model[-1]

#### Build keras model
from keras import optimizers
from keras import backend as K
from keras.losses import kullback_leibler_divergence,mean_squared_error
from keras.callbacks import ReduceLROnPlateau, EarlyStopping
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout, Activation, BatchNormalization
import numpy as np

keras_model = Sequential()
keras_model.add(Conv2D(32, (8, 8), strides=(4, 4), input_shape=(84, 84, 4)))
keras_model.add(Activation('relu'))
keras_model.add(Conv2D(64, (4, 4), strides=(2, 2)))
keras_model.add(Activation('relu'))
keras_model.add(Conv2D(64, (3, 3), strides=(1, 1)))
keras_model.add(Activation('relu'))
keras_model.add(Flatten())
keras_model.add(Dense(512))
keras_model.add(Activation('relu'))
keras_model.add(Dense(6))

### transfer the weights from pkl model to keras model
j_list = [0,2,4,7,9]  
for i in range(5):
    w1 = np.squeeze(pkl_weights[2*i+1])
    w2 = np.squeeze(pkl_weights[2*i+2])
    layer_weights = [w1, w2]
    keras_model.layers[j_list[i]].set_weights(layer_weights)
### Test the performace of the saved keras model
from stable_baselines.common.cmd_util import make_atari_env
from stable_baselines.common.policies import CnnPolicy
from stable_baselines.common.vec_env import VecFrameStack
env = make_atari_env('{}NoFrameskip-v4'.format(game), num_env=1, seed=0)
env = VecFrameStack(env, n_stack=4)
obs = env.reset()
while True:
    actions = keras_model.predict(obs)
    action = np.argmax(actions[0])
    obs, rewards, dones, infos = env.step([action])
    episode_infos = infos[0].get('episode')
    if episode_infos is not None:
        print("Atari Episode Score: {:.2f}".format(episode_infos['r']))
        print("Atari Episode Length", episode_infos['l'])
        break
```
The model weights can be converted, but the performance indicate that the there is still some issues. The accumulated reward of such converted keras model is -20.
Could you please share your insight on this?

**Comment by araffin** [comment] 2020-03-12 09:29
It seems your forgot to normalize the image... (cf doc) by dividing by 255

**Comment by QuXinghuaNTU** [comment] 2020-03-12 11:56
> It seems your forgot to normalize the image... (cf doc) by dividing by 255

Thanks. It finally works. Will update the code here.

**Closed** 2020-03-12 20:43 UTC
Labels: No tech support, duplicate, question
