### ISSUE TITLE
[question] Trained networks: Linux vs Windows

### ISSUE THREAD

**Issue by langan7** [hill-a/stable-baselines#1024] opened 2020-10-20 08:51 UTC
I have trained a network using PPO2.learn() on a Linux machine and saved the model using PPO2.learn(). My problem comes when I try to load the model on a Windows machine using PPO2.load(), I get an error such as:
Exception has occurred: AttributeError
module 'types' has no attribute 'CellType'

I can PPO2.load() models that were trained on my Windows machine with no problem. Both Windows and Linux machines have the same library versions installed on them.

In addition, I tried swapping a "data" file (inside the output .zip folder) from Windows to Linux model and it worked --> I could load the Linux model with a Windows data file inside it. 

My bet is that the Linux data file is written in a different sintax, that the Windows load cannot understand. Is there any way around this? There is a reason behind doing everything on Windows, so I'm trying to avoid any answers that require sticking with a Linux machine.

**System Info**
Everything installed using conda except for stable-baselines
Python 3.7
Cloudpickle 1.6 **EDIT** both have 1.6 version now, still doesn't work
Gym 0.17.3
Tensorflow 1.14
Stable-baselines 2.10.1 (pip install)

Thanks in advance

**Comment by araffin** [comment] 2020-10-20 09:05
Hello,
Please fill the issue template completely (missing traceback, python version and cloudpickle version)

**Comment by langan7** [comment] 2020-10-20 09:54
Is there a way to solve this issue? 
cloudpickle is installed when I install gym I think, I have the same gym version on both machines but on Windows it installs cloudpickle=1.3 and Linux 1.6

**Comment by araffin** [comment] 2020-10-20 10:00
You can force the cloudpickle version by using `pip install cloudpickle==1.6` after installing gym (this issue should be solved with newer gym version, see https://github.com/openai/gym/pull/2032)

**Comment by langan7** [comment] 2020-10-20 10:09
Thanks!! Still not working with same cloudpickle version, though

**Comment by araffin** [comment] 2020-10-20 10:15
> Still not working with same cloudpickle version, though

Well, did you try saving and loading now (and not with a previous run?).
The full traceback of your error is still missing. 

You may also want to consider windows sub-system for linux (as our continuous integration only run on linux, we cannot ensure that everything will run smoothly on windows).

Anyway, it does not seem to come from stable-baselines but from other libraries... so I will close this issue.

**Comment by langan7** [comment] 2020-10-20 10:18
Well, I tried new version on windows loading an old file from Linux (which was already run with the newer cloudpickle version) It should work. 
Is it possible that there's something in the data file saved in the .zip that has a different sintax in Linux than windows, which causes this error to happen?

**Comment by araffin** [comment] 2020-10-20 10:27
Again, please fill the issue template completely (minimal code to reproduce, not using a custom env + full traceback)

**Comment by Miffyli** [comment] 2020-10-20 10:40
@araffin I can give this a try at some point with stable-baselines3. Given how common these errors are I should probably look into the fallbacks/options for dealing with situations like this in SB3 soon enough...

**Comment by araffin** [comment] 2020-10-20 10:50
>I can give this a try at some point with stable-baselines3.

thanks =)
in fact, with github actions, we should be able to test mac os  and windows for SB3.

**Comment by Miffyli** [comment] 2020-10-20 22:15
Ok so I created an identical environment on Windows and Linux and was able to load without errors, but this required to match Python versions exactly (as expected, because cloudpickle is not designed to cross Python versions) and cloudpickle versions. I was using current `master` of stable-baselines for this.

But regardless, this just serves to remind that I should probably look into the tools for dealing with these scenarios in SB3.

@langan7 
You may close this issue if you have no further questions or issues related to stable-baselines.

**Closed** 2020-10-21 09:29 UTC
Labels: more information needed, question, windows

**Comment by ariskoutris** [comment] 2021-06-04 16:33
> pip install cloudpickle==1.6

This solved the issue for me. Thank you!
