### ISSUE TITLE
Writing Tensorboard log files causes Google Colab runtime to crash.

### ISSUE THREAD

**Issue by Noahyt** [hill-a/stable-baselines#80] opened 2018-11-16 20:23 UTC
**Describe the bug**
When running in a Google Colab, if a model is set up to write tensorboard, the runtime crashes after the first write out (typically in the call to `model.learn()`). 

**Code example**
Running the example for `ppo2` (or any other algorithm) with the addition of the `tensorbaord_log` argument.  E.g.
```
model = PPO2(MlpPolicy, env, verbose=1, tensorboard_log='./log')
model.learn(25000)  # Causes runtime to crash.
```

**System Info**
Google Colab with dependencies installed as per the documented example Colab [here](https://colab.research.google.com/drive/1KoAQ1C_BNtGV3sVvZCnNZaER9rstmy0s).

**Comment by araffin** [comment] 2018-11-17 09:48
Hello,

Could you provide a colab notebook with the error?
I tried reproducing the error but I did not succeed...
It seems that the issue may comes from colab and not stable-baselines.

Associated notebook: https://colab.research.google.com/drive/1LXeHFoo6-r_3nzBeE2TEJdlJxv_3D5PG

**Comment by Charelvanhoof** [comment] 2018-11-18 19:01
I had the similar crash in my colab notebook(s).
Interesting enough you example notebooks runs fine in the playground
But this crashed
```
# @title train the agent
env_id = 'BreakoutNoFrameskip-v4'
training_length = 3000000
monitor_dir = '/content/drive/My Drive/breakoutA2C'

env = make_atari_env(env_id, num_env=4, seed=0)
env = VecFrameStack(env, n_stack=4)

model = A2C.load(monitor_dir + "/a2c_breakout_10000000", env=env, tensorboard_log='./log')

model.learn(total_timesteps=training_length)

print("Training complete")

# Save the agent
model.save(monitor_dir + "/a2c_breakout_"+ str(training_length))


```

**Comment by Charelvanhoof** [comment] 2018-11-18 19:13
Interesting, peeling the union and copy-paste lines of code back into the playground, this stil works

```
#env = gym.make('BreakoutNoFrameskip-v4')
env = make_atari_env('BreakoutNoFrameskip-v4', num_env=4, seed=0)
env = VecFrameStack(env, n_stack=4)

#model = PPO2(MlpPolicy, env, verbose=1, tensorboard_log='./log')
model = A2C(MlpPolicy, env, verbose=1, tensorboard_log='./log')
```
so it is maybe the load parameter, I did not have tensorboard logging on when I saved the model, maybe that is the problem, will test some more

**Comment by Charelvanhoof** [comment] 2018-11-18 19:34
it all worked correctly
```
#env = gym.make('BreakoutNoFrameskip-v4')
env = make_atari_env('BreakoutNoFrameskip-v4', num_env=4, seed=0)
env = VecFrameStack(env, n_stack=4)

#model = PPO2(MlpPolicy, env, verbose=1, tensorboard_log='./log')
model = A2C(MlpPolicy, env, verbose=1)
model.learn(2000)
model.save('./test')
model = A2C.load('./test', env=env, tensorboard_log='./log2')
model.learn(2000)
````

No crash

**Comment by Charelvanhoof** [comment] 2018-11-18 19:36
Found it: when you put it on accelerator = GPU (iso none). Then the last model.learn(2000) line crashes.

**Comment by araffin** [comment] 2018-11-19 10:14
Yep, I tried it myself and it restarts the runtime... the problem is that no errors are produced, it seems more an issue related to colab, I'm afraid we cannot really do something, what do you think?

**Comment by araffin** [comment] 2019-02-08 16:23
@Charelvanhoof can you check again with both master and `enhancements` branches?

I retried and could not reproduce the bug (even with GPU accelerator).

To install:
```
git clone -b enhancements https://github.com/hill-a/stable-baselines.git
cd stable-baselines/
pip install -e .
```

**Comment by Charelvanhoof** [comment] 2019-02-16 16:20
Tested it on Colab and indeed does not crash anymore on GPU acceleration.


```
env = make_atari_env('BreakoutNoFrameskip-v4', num_env=4, seed=0)
env = VecFrameStack(env, n_stack=4)
model = PPO2(MlpPolicy, env, verbose=1, tensorboard_log='./PPO2_breakout_tensorboard/')
model.learn(2000)

```

works, the directory is created, etc.

But cant visualize the data yet. If I follow the instructions and run:  

`tensorboard --logdir ./PPO2_breakout_tensorboard/`


I get:  


```
tensorboard --logdir ./PPO2_breakout_tensorboard/  
               ^  
SyntaxError: invalid syntax
```

**Comment by araffin** [comment] 2019-02-16 17:34
Ok good news.
Closing then.

The error you get is because you are running non python command in a python prompt. You to prefix your command "!" , although here, you will need additional tweaking to redirect Google colab virtual machine port to an accessible one via the browser (for that, Google is your friend). Anyway, this is not related anymore to SB.

**Closed by araffin** 2019-02-16 17:34 UTC
Labels: colab

**Comment by Charelvanhoof** [comment] 2019-02-16 19:05
Hi Araffin,

You are right, in fact I already had it figured out in the past and your feedback triggered me to find it back. Leaving some notes for maybe helping other people

First run
```
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip 
```

Next:
```
LOG_DIR = './PPO2_breakout_tensorboard/'
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
)

get_ipython().system_raw('./ngrok http 6006 &')

! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"
```

The link will bring you to the tensorboard.
