### ISSUE TITLE
[Question] Cannot run build_graph (gail/adversary.py) for box(210,160,3)observation

### ISSUE THREAD

**Issue by Remosy** [hill-a/stable-baselines#465] opened 2019-09-04 07:47 UTC
**Describe the bug**
The env **[Ice Hockey](https://gym.openai.com/envs/IceHockey-v0/)** has Discrete(18) actions and Box(210,160,3) observation

When I run below code, I get error: 
```TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type uint8 of argument 'x'.```

When debug:
it stucks on my code: ```model = GAIL("MlpPolicy", 'IceHockey-v0', dataset, verbose=1)```. 
when "step into" this line, the error is caused by the math operations(line 121 in gail/adversary.py).
```python
obs = (obs_ph - self.obs_rms.mean) / self.obs_rms.std
```
**obs_ph** has dtype:unit8
![Screen Shot 2019-09-04 at 4 11 53 pm](https://user-images.githubusercontent.com/7675410/64229984-bf832900-cf2e-11e9-9d0d-fae52caa5ea7.png)

**self.obs_rms.mean** has dtype:float32
![Screen Shot 2019-09-04 at 4 10 12 pm](https://user-images.githubusercontent.com/7675410/64229898-7d59e780-cf2e-11e9-9dea-b1d60d592843.png)

**Code example**
```python
import gym
from stable_baselines import GAIL
from stable_baselines.gail import ExpertDataset
from stable_baselines import TRPO
from stable_baselines.gail import generate_expert_traj

model = TRPO('MlpPolicy', 'IceHockey-v0', verbose=1)
# run about 5 mins
generate_expert_traj(model, 'expert_icehockey', n_timesteps=100, n_episodes=10)
dataset = ExpertDataset(expert_path='expert_icehockey.npz', traj_limitation=10, verbose=1)

model = GAIL("MlpPolicy", 'IceHockey-v0', dataset, verbose=1)
model.learn(total_timesteps=1000)
model.save("gail_icehockey")
```

**System Info**
python 3.7, pip 19.1.1
Has downloaded newest version libraries from [here](https://stable-baselines.readthedocs.io/en/master/guide/install.html):
openmpi
stable-baselines
stable-baselines[mpi]
tensorflow

**Comment by araffin** [comment] 2019-09-04 07:57
Hello,
From the [documentation](https://stable-baselines.readthedocs.io/en/master/modules/gail.html):
"Images are not yet handled properly by the current implementation"

Duplicate of https://github.com/hill-a/stable-baselines/issues/271

**Closed by araffin** 2019-09-04 07:57 UTC
Labels: RTFM, duplicate, question
