### ISSUE TITLE
Issues with loading PPO2 model 

### ISSUE THREAD

**Issue by lppier** [hill-a/stable-baselines#934] opened 2020-07-09 11:40 UTC
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.

If your issue is related to a custom gym environment, please check it first using:

```python
from stable_baselines.common.atari_wrappers import make_atari
# from stable_baselines import DQN
from stable_baselines.common.policies import MlpPolicy, CnnPolicy
# from stable_baselines.deepq.policies import MlpPolicy, CnnPolicy
from stable_baselines import PPO2
import matplotlib.pyplot as plt
import os
from stable_baselines.bench import Monitor
from stable_baselines.results_plotter import load_results, ts2xy
from stable_baselines.common.callbacks import BaseCallback
import numpy as np
from stable_baselines.common.callbacks import CheckpointCallback
from stable_baselines.common.vec_env import DummyVecEnv
import retro

load_model = True
evaluation = True

env = retro.make('SonicTheHedgehog2-Genesis', 'EmeraldHillZone.Act1',
                 scenario="/home/pier/PycharmProjects/retro/retro/data/stable/SonicTheHedgehog2-Genesis/scenario.json")

model = PPO2(CnnPolicy, env, verbose=1, tensorboard_log="/tmp/sonic2/", learning_rate=0.0001)
if load_model:
    model.load("sonic_final.zip")
    # n_cpu = 8
    env = DummyVecEnv([lambda: env])
    model.set_env(env)
    print("Loaded from previous model!")

if not evaluation:
    # Save a checkpoint every 1000 steps
    checkpoint_callback = CheckpointCallback(save_freq=1000, save_path='./logs/sonic2/',
                                             name_prefix='rl_model')
    model.learn(total_timesteps=500_000, callback=checkpoint_callback)
    model.save("sonic_final.zip")
```

**Describe the bug**
I have been training and saving my PPO2 model with stable baselines and retro. 
The issue is that I don't think loading the model helps - I trained for 1-2 days. 
Sonic is just doing random jumps. 
Simply training for 10000 steps, sonic manages to move forward, so I'm fairly certain the saved model is not being used. 
I tried saving the model both ways, using the checkpoint_callback and mode.save()

Please help me with this, anyone? Thanks.

**Comment by araffin** [comment] 2020-07-09 11:49
Duplicate of https://github.com/hill-a/stable-baselines/issues/30#issuecomment-423694592

**Closed** 2020-07-16 19:14 UTC
Labels: RTFM, duplicate, question
