### ISSUE TITLE
Error running custom_cartpole.py

### ISSUE THREAD

**Issue by aakash94** [hill-a/stable-baselines#812] opened 2020-04-18 15:35 UTC
**Error observed when running `stable_baselines\deepq\experiments\custom_cartpole.py` as is**

```
ValueError: Cannot feed value of shape (32,) for Tensor 'deepq/double_q/input/Ob:0', which has shape '(?, 4)'

```
above error is observed when the following line is called (line 82, custom_cartpole.py), it usually gets there in around 50 episodes (1000 steps)
```python

train(obses_t, actions, rewards, obses_tp1, dones, np.ones_like(rewards))

```
**What's causing this?**
the `train` function call in line 82 of the file expects another parameter for `double_q` where it is instead getting the `dones`

**Why?**
The default value of `double_q` is initialized as `True` in the `build_train` function in `stable_baselines\deepq\build_graph.py` (line 323)
```python

def build_train(q_func, ob_space, ac_space, optimizer, sess, grad_norm_clipping=None,
                gamma=1.0, double_q=True, scope="deepq", reuse=None,
                param_noise=False, param_noise_filter_func=None, full_tensorboard_log=False)

```
and no value is passed for `double_q` when the above is called in `custom_cartpole.py` (line 31)
```python

act, train, update_target, _ = deepq.build_train(
        q_func=CustomPolicy,
        ob_space=env.observation_space,
        ac_space=env.action_space,
        optimizer=tf.train.AdamOptimizer(learning_rate=5e-4),
        sess=sess
)

```

**The Fix**
passing `False` for `double_q` when calling `deepq.build_train` in `custom_catrpole.py` fixes the issue observed above and does not raise errors when `train` is called
```python

act, train, update_target, _ = deepq.build_train(
        q_func=CustomPolicy,
        ob_space=env.observation_space,
        ac_space=env.action_space,
        optimizer=tf.train.AdamOptimizer(learning_rate=5e-4),
        sess=sess,
        double_q=False
)


```

**System Info**
 * How the library was used : from source on Windows10, libraries installed using Conda, Code ran and edited in Visual Studio Code
 * GPU model and configuration : GeForce GTX 1050 mobile
 * Python version : 3.7.6
 * Tensorflow version : 1.14.0

**Comment by aakash94** [comment] 2020-04-18 15:47
I have the fix on my fork of the branch, can raise a Pull Request if required.

**Comment by araffin** [comment] 2020-04-18 19:08
Looks like a duplicate of #810 .

As mentioned, I would be rather in favor of deleting that file (and the mentions of that file in the doc) as it is an old file that is not apparently keep up to date and that does not follow the recommended way of using SB.

**Comment by aakash94** [comment] 2020-04-18 21:23
@araffin I made the discussed changes [here](https://github.com/aakash94/stable-baselines/commit/3b741c8aecd28fa611a8711e8549dc6636a12c0e). Before I raise a PR, I would like to know which section of the changelog would these fit the best? deprecation or bug-fixes or breaking changes?

**Comment by Miffyli** [comment] 2020-04-18 21:36
@aakash94 

I would go with "documentation" section, as this has no relation to functional code side. Just an example of how to use the underlying things (but which was not kept up to date).

**Closed** 2020-04-19 12:18 UTC
Labels: bug, duplicate
