### ISSUE TITLE
full_tensorboard_log=True in PPO2

### ISSUE THREAD

**Issue by saeid93** [hill-a/stable-baselines#827] opened 2020-04-25 00:00 UTC
When I try running the following code:

```
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2

# multiprocess environment
env = make_vec_env('CartPole-v1', n_envs=4)

model = PPO2(MlpPolicy, env, verbose=1, full_tensorboard_log=True, tensorboard_log="./a2c_cartpole_tensorboard/")
model.learn(total_timesteps=25000)
model.save("ppo2_cartpole")
```

I get the following error:

```
INFO:tensorflow:Summary name model/pi_fc0/w:0 is illegal; using model/pi_fc0/w_0 instead.
INFO:tensorflow:Summary name model/pi_fc0/b:0 is illegal; using model/pi_fc0/b_0 instead.
INFO:tensorflow:Summary name model/vf_fc0/w:0 is illegal; using model/vf_fc0/w_0 instead.
INFO:tensorflow:Summary name model/vf_fc0/b:0 is illegal; using model/vf_fc0/b_0 instead.
INFO:tensorflow:Summary name model/pi_fc1/w:0 is illegal; using model/pi_fc1/w_0 instead.
INFO:tensorflow:Summary name model/pi_fc1/b:0 is illegal; using model/pi_fc1/b_0 instead.
INFO:tensorflow:Summary name model/vf_fc1/w:0 is illegal; using model/vf_fc1/w_0 instead.
INFO:tensorflow:Summary name model/vf_fc1/b:0 is illegal; using model/vf_fc1/b_0 instead.
INFO:tensorflow:Summary name model/vf/w:0 is illegal; using model/vf/w_0 instead.
INFO:tensorflow:Summary name model/vf/b:0 is illegal; using model/vf/b_0 instead.
INFO:tensorflow:Summary name model/pi/w:0 is illegal; using model/pi/w_0 instead.
INFO:tensorflow:Summary name model/pi/b:0 is illegal; using model/pi/b_0 instead.
INFO:tensorflow:Summary name model/q/w:0 is illegal; using model/q/w_0 instead.
INFO:tensorflow:Summary name model/q/b:0 is illegal; using model/q/b_0 instead.
--------------------------------------
| approxkl           | 0.00012277898 |
| clipfrac           | 0.0           |
| ep_len_mean        | 22.1          |
| ep_reward_mean     | 22.1          |
| explained_variance | -0.00965      |
| fps                | 803           |
| n_updates          | 1             |
| policy_entropy     | 0.6930225     |
| policy_loss        | -0.0018470337 |
| serial_timesteps   | 128           |
| time_elapsed       | 0.000114      |
| total_timesteps    | 512           |
| value_loss         | 46.814804     |
--------------------------------------
--------------------------------------
| approxkl           | 0.00013410364 |
| clipfrac           | 0.0           |
| ep_len_mean        | 41.7          |
| ep_reward_mean     | 41.7          |
| explained_variance | -0.0203       |
| fps                | 1740          |
| n_updates          | 16            |
| policy_entropy     | 0.6306607     |
| policy_loss        | -0.0032595946 |
| serial_timesteps   | 2048          |
| time_elapsed       | 4.9           |
| total_timesteps    | 8192          |
| value_loss         | 57.992912     |
--------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-e33cf98cac86> in <module>
      9 
     10 model = PPO2(MlpPolicy, env, verbose=1, full_tensorboard_log=True, tensorboard_log="./a2c_cartpole_tensorboard/")
---> 11 model.learn(total_timesteps=25000)
     12 model.save("ppo2_cartpole")
     13 

~/EdgeSysPaper/.venv/lib64/python3.6/site-packages/stable_baselines/ppo2/ppo2.py in learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps)
    358                             slices = (arr[mbinds] for arr in (obs, returns, masks, actions, values, neglogpacs))
    359                             mb_loss_vals.append(self._train_step(lr_now, cliprange_now, *slices, writer=writer,
--> 360                                                                  update=timestep, cliprange_vf=cliprange_vf_now))
    361                 else:  # recurrent version
    362                     update_fac = self.n_batch // self.nminibatches // self.noptepochs // self.n_steps + 1

~/EdgeSysPaper/.venv/lib64/python3.6/site-packages/stable_baselines/ppo2/ppo2.py in _train_step(self, learning_rate, cliprange, obs, returns, masks, actions, values, neglogpacs, update, writer, states, cliprange_vf)
    288                     [self.summary, self.pg_loss, self.vf_loss, self.entropy, self.approxkl, self.clipfrac, self._train],
    289                     td_map, options=run_options, run_metadata=run_metadata)
--> 290                 writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
    291             

- [ ] else:

    292                 summary, policy_loss, value_loss, policy_entropy, approxkl, clipfrac, _ = self.sess.run(

~/EdgeSysPaper/.venv/lib64/python3.6/site-packages/tensorflow_core/python/summary/writer/writer.py in add_run_metadata(self, run_metadata, tag, global_step)
    262     """
    263     if tag in self._session_run_tags:
--> 264       raise ValueError("The provided tag was already used for this event type")
    265     self._session_run_tags[tag] = True
    266 

ValueError: The provided tag was already used for this event type

```

However, it works fine with full_tensorboard_log=False, Is it a bug or I'm using it wrong?

**Comment by araffin** [comment] 2020-04-25 09:58
Duplicate of #472 
maybe be closed by https://github.com/hill-a/stable-baselines/pull/822

**Closed by araffin** 2020-04-25 09:58 UTC
Labels: bug, duplicate
