### ISSUE TITLE
 [question] Multiple agents with different RL Algorthims 

### ISSUE THREAD

**Issue by Degiorgio** [hill-a/stable-baselines#705] opened 2020-02-24 21:19 UTC
Does  stable-basline  support multiple agents with different RL algorithms? For instance, one agent who behaves according to reactive policy learned by DQN  and another agent that behaves according to a policy learned by PPO 

If so can you point me to a basic example of this setup? Thank you!

**Comment by Miffyli** [comment] 2020-02-24 21:33
Would these be pre-trained models that are not learning? Then you could simply load up the two agents and use them "manually", [like in this example](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading). 

If one or more of the agents are learning (e.g. self-play type of setup), that is trickier, see #181 and #423. If only one of the agents learns, you could embed the other players into the environment, while learning agent calls the `learn`.

**Comment by Degiorgio** [comment] 2020-02-24 23:25
@Miffyli  This is in multi-agent environment. Example a grid world, where two agents are trained are rewarded for collected apples, the agents themselves are not pre-trained and need to be trained together

**Comment by Miffyli** [comment] 2020-02-25 08:29
@Degiorgio 
This is not (easily) possible with stable-baselines (see the issues I referred to). You'd have to play around with environments. [rllib](https://ray.readthedocs.io/en/latest/rllib.html) is more oriented towards such setups.

**Comment by araffin** [comment] 2020-02-28 10:04
Closing this one as it is a duplicate of the two issues mentioned above.

**Closed by araffin** 2020-02-28 10:04 UTC
Labels: duplicate, question
