### ISSUE TITLE
Support for input space of Dict format

### ISSUE THREAD

**Issue by aveen-d** [hill-a/stable-baselines#1045] opened 2020-11-23 16:40 UTC
Hi, I am using a custom environment for which the observation space is spaces.Dict. When I tried to run DQN or A2C baseline models I got an error saying the input space Dict is not implemented. Is there a way around with this. The observation space is space. Dict{
'rgb': array((256,256,3)),
'depth': array((256,256,1)),
'compass': array((3,1))
}

**Comment by Miffyli** [comment] 2020-11-23 16:42
Duplicate of #100 and #947 

There is no support for dict spaces and no easy way around it. A workaround is to combine all the data you have into a single "image" array and then split it inside network accordingly. See e.g. https://github.com/hill-a/stable-baselines/issues/947#issuecomment-663846444

**Closed** 2020-11-23 16:43 UTC
Labels: bug, duplicate
