### ISSUE TITLE
[question] Model Tune?

### ISSUE THREAD

**Issue by jheffez** [hill-a/stable-baselines#611] opened 2019-12-11 14:16 UTC
I understand that there is a way to tune hyperparameter. Is there a way to tune the actual model (number of layers and tensors) to speed-up training?
If not, is it possible to integrate something like [adanet](https://github.com/tensorflow/adanet)?

**Comment by araffin** [comment] 2019-12-11 16:37
Duplicate of https://github.com/araffin/rl-baselines-zoo/issues/57

**Closed by araffin** 2019-12-11 16:37 UTC
Labels: duplicate, question
