### ISSUE TITLE
How to fix an initialization for PPO2

### ISSUE THREAD

**Issue by sophiagu** [hill-a/stable-baselines#1028] opened 2020-10-26 20:32 UTC
I was using PPO2 to train my agent. And I found that different runs of my training yielded very different results using the same hyperparameters: some yielded pretty good results but some were totally broken (not learning at all). So I guess it's probably due to a different initialization of weights during each run. If my guess is correct (and please let me know if others have encountered similar problems), may I know how to fix an initialization for PPO2?

**Comment by Miffyli** [comment] 2020-10-26 20:35
This is expected from RL agents, both because of the random initialization but also because of stochastic environments. See [reproducibility](https://stable-baselines.readthedocs.io/en/master/guide/algos.html#reproducibility) in docs. 

You may close this issue if that answers your question.

**Comment by araffin** [comment] 2020-10-26 20:56
From the ["RL tips and tricks" section](https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html):
"
Reinforcement Learning differs from other machine learning methods in several ways. The data used to train the agent is collected through interactions with the environment by the agent itself (compared to supervised learning where you have a fixed dataset for instance). This dependence can lead to vicious circle: if the agent collects poor quality data (e.g., trajectories with no rewards), then it will not improve and continue to amass bad trajectories.

This factor, among others, explains that results in RL may vary from one run to another (i.e., when only the seed of the pseudo-random generator changes). For this reason, you should always do several runs to have quantitative results.
"

**Comment by sophiagu** [comment] 2020-10-26 21:08
These advice are helpful! Thank you!

I'll close this issue once I've experimented with the suggestions.

**Closed** 2020-10-26 23:46 UTC
Labels: RTFM, question
