### ISSUE TITLE
Can't import callbacks

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#721] opened 2020-03-05 14:35 UTC
When I try to import the callbacks I get the error `ModuleNotFoundError: No module named 'stable_baselines.common.callbacks'`.

I'm using the most recent release of stable-baselines:

```bash
> pip freeze | grep stable-baselines
stable-baselines==2.9.0
```

**Comment by Miffyli** [comment] 2020-03-05 14:39
Closing as a duplicate of #719 

tl;dr: Version with callbacks is not on PyPi. Install from github.

**Closed by Miffyli** 2020-03-05 14:39 UTC

**Comment by araffin** [comment] 2020-03-05 15:52
@Miffyli I think we either need to default the doc on the latest release or write a warning
anyway, I plan to finish #200 this week end so we can do a pip release afterward.
