### ISSUE TITLE
[QUESTION] How to add Dropout?

### ISSUE THREAD

**Issue by jandevries123** [hill-a/stable-baselines#936] opened 2020-07-09 20:00 UTC
Hello,

I was wondering how one could add dropout to their layers in the Stable Baselines library?
I figured i'd have to use the custom policy functions illustrated at https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html , however i couldn't make more out of it than that it allowes you to change network layers and activation functions, not stuff like how to add a layer regularizer, am i missing something?

thanks in advance.

**Comment by Miffyli** [comment] 2020-07-09 20:08
Duplicate of [multiple issues](https://github.com/hill-a/stable-baselines/issues?q=dropout). The policies are the networks you need to modify to achieve this. I suggest you take a look at linked issues and others related to custom policies.

Closing as duplicate.

**Closed by Miffyli** 2020-07-09 20:08 UTC

**Comment by jandevries123** [comment] 2020-07-10 10:39
I already did before asking and they didn't gave any clear direction?

**Comment by Miffyli** [comment] 2020-07-10 11:56
Both #833 and #395 have examples of people using dropout.

**Comment by jandevries123** [comment] 2020-12-05 14:46
please delete issue

**Comment by jandevries123** [comment] 2021-01-07 08:32
Please delete issue
