### ISSUE TITLE
Can an example of a monitoring callback based on episodes instead of timestep's be added?

### ISSUE THREAD

**Issue by justinkterry** [hill-a/stable-baselines#544] opened 2019-11-08 01:48 UTC
In the example of using callback to monitor training [here](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training), the logging is done is solely in terms of time steps, not episodes. Usually, when monitoring, you care much more about episodes than time steps, and how to change the callback to log performance every episode instead of time step isn't clear from the example given. Can that an example be added for that, or at a minimum can someone please tell me how to do it since I can't figure it out?

**Comment by Miffyli** [comment] 2019-11-08 14:41
The monitor file created by `Monitor` wrapper prints out one line per episode, each line containing reward from that episode. You can then read and plot this CSV file as you please. The function used in the in the example is a helper in case you want to get started fast.

**Comment by araffin** [comment] 2019-11-08 16:07
Hello,

I think this issue may be a duplicate of that one: https://github.com/hill-a/stable-baselines/issues/62

**Closed** 2019-11-18 10:13 UTC
Labels: duplicate, question
