### ISSUE TITLE
writer.add_run_metadata() failed to add tag that already used

### ISSUE THREAD

**Issue by wiekern** [hill-a/stable-baselines#598] opened 2019-12-04 11:19 UTC
**Describe the bug**
The problem appears as `update * update_fac` can give one number by different combinations of (update, update_fac), for example 12 could be represented by 3*4 or 2*6, which leads to the same tag.

writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))

```
A clear and concise description of what the bug is.
Traceback (most recent call last):
  File ".\ppo2_test.py", line 139, in <module>
    model.learn(total_timesteps=10000)
  File "C:\Users\wiekern\Desktop\IMA\latest_code\rl-agentgen3\03_RL_Agents\02_Modified_Stable_Baselines_RL_Implementations\stable_baselines\ppo2\ppo2.py", line 353, in learn
    update=timestep, cliprange_vf=cliprange_vf_now))
  File "C:\Users\wiekern\Desktop\IMA\latest_code\rl-agentgen3\03_RL_Agents\02_Modified_Stable_Baselines_RL_Implementations\stable_baselines\ppo2\ppo2.py", line 294, in _train_step
    writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
  File "C:\Users\wiekern\Anaconda3\envs\camuffel_cpu\lib\site-packages\tensorflow\python\summary\writer\writer.py", line 263, in add_run_metadata
    raise ValueError("The provided tag was already used for this event type")
ValueError: The provided tag was already used for this event type
```
**Code example**
```python
    import gym

    from stable_baselines.common.policies import MlpPolicy
    from stable_baselines.common.vec_env import DummyVecEnv
    from stable_baselines import PPO2

    # Create and wrap the environment
    env = gym.make('CartPole-v1')
    env = DummyVecEnv([lambda: env])

    model = PPO2(MlpPolicy, env,
                 verbose=1,
                 tensorboard_log='./',
                 full_tensorboard_log=True
                 )

    model.learn(total_timesteps=10000)
```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: conda install
 * GPU models and configuration: only using CPU
 * Python version: 3.6.9
 * Tensorflow version: 1.12.0

**Comment by araffin** [comment] 2019-12-04 12:17
Hello,
i think this is a duplicate of https://github.com/hill-a/stable-baselines/issues/472

**Comment by wiekern** [comment] 2019-12-04 12:19
Hi, you are right. it's duplicated. thanks for reminding me!

**Comment by araffin** [comment] 2019-12-04 12:47
Closing this in favor of #472 then. Again, we would appreciate a PR that solves that issue.

**Closed by araffin** 2019-12-04 12:47 UTC
Labels: bug, duplicate
