### ISSUE TITLE
Test performance is different when reload the trained model

### ISSUE THREAD

**Issue by binderwang** [hill-a/stable-baselines#26] opened 2018-09-20 02:37 UTC
Hi hill-a,
thank you for your elegant work. According to your example(like PPO2, ACER), when learned a model and save it, then load it for test, it works well. But if I reload the saved .pkl file without learning, it doesn't work so well as before. Did I reload right? Thanks again.
***That's what I did to test the learned model:***
import gym

from stable_baselines.common.policies import MlpPolicy, MlpLstmPolicy, MlpLnLstmPolicy, \
    CnnPolicy, CnnLstmPolicy, CnnLnLstmPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines import ACER

n_cpu = 4
env = SubprocVecEnv([lambda: gym.make('CartPole-v1') for i in range(n_cpu)])
model = ACER.load("acer_cartpole")
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

**Comment by araffin** [comment] 2018-09-26 08:37
Hello,
To answer your question i need additional context (system info, complete minimal script to reproduce what you have (the training script is missing), ...). Please follow the issue template: https://github.com/hill-a/stable-baselines/blob/master/.github/ISSUE_TEMPLATE/issue-template.md

When you say it does not work so well could you provide us with mean reward over 100 episodes before and after ?

**Comment by araffin** [comment] 2018-10-14 20:03
@binderwang when you it does not work as well as before, can you provide metric? (e.g., mean over 100 test episodes)

**Comment by araffin** [comment] 2018-10-20 15:36
I'm closing this issue because we don't have enough information to reproduce the potential bug. Feel free to re-open if you add more information.

**Closed by araffin** 2018-10-20 15:36 UTC
