### ISSUE TITLE
Cannot enjoy the trained agents when using stable-baselines3, rl-baselines3-zoo

### ISSUE THREAD

**Issue by Litao917** [hill-a/stable-baselines#878] opened 2020-06-03 13:04 UTC
After cloning the rl-baselines3-zoo, I was trying to train my own agent.
 By :
**python train.py --algo algo_name --env env_id**
After that, I used 
**python enjoy.py --algo algo_name --env env_id**
Specifically it is 
**python enjoy.py --algo td3 --env AntBulletEnv-v0 -f logs/**
However I got the following problem

`Loading latest experiment, id=2
pybullet build time: Jun  2 2020 06:49:02
/home/dell/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 42, in _worker
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "enjoy.py", line 201, in <module>
    main()
  File "enjoy.py", line 116, in main
    model = ALGOS[algo].load(model_path, env=env)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 362, in load
    model._setup_model()
  File "/home/dell/stable-baselines3/stable_baselines3/td3/td3.py", line 95, in _setup_model
    super(TD3, self)._setup_model()
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 729, in _setup_model
    self.set_random_seed(self.seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 461, in set_random_seed
    self.env.seed(seed)
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in seed
    return [remote.recv() for remote in self.remotes]
  File "/home/dell/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 112, in <listcomp>
    return [remote.recv() for remote in self.remotes]
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/dell/anaconda3/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
`

My environment is 
Ubuntu 18.04
Python 3.8.3
PyTorch 1.5.0
Gym 0.17.2

Thank you in advance.

**Comment by araffin** [comment] 2020-06-03 13:19
Hello,

Could you reformat your traceback using Markdown code block? (cf issue template)

Btw, this issue belong to the rl-baselines3-zoo repo I suppose...

**Comment by araffin** [comment] 2020-06-03 13:20
Duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/18

**Closed by araffin** 2020-06-03 13:20 UTC
Labels: more information needed, v3
