### ISSUE TITLE
Can't import evaluation function in colab

### ISSUE THREAD

**Issue by drozzy** [hill-a/stable-baselines#867] opened 2020-05-20 22:58 UTC
For some reason using the stable-baselines from **colab** and importing `evaluate_policy` fails.

Here is my complete code:

```
!pip install stable-baselines -q
# stable_baselines needs tensorflow 1 
%tensorflow_version 1.x
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines import PPO2
from stable_baselines.common.evaluation import evaluate_policy
import gym
import numpy as np
```

and here is the error:

```
TensorFlow 1.x selected.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-9a251b4aa149> in <module>()
      5 from stable_baselines import PPO2
      
----> 7 from stable_baselines.common.evaluation import evaluate_policy
      8 import gym
      9 import numpy as np

ModuleNotFoundError: No module named 'stable_baselines.common.evaluation'
```

**Comment by araffin** [comment] 2020-05-21 07:08
Hello,
please take a look at the provided notebooks, the order is important ;):
https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/master/stable_baselines_getting_started.ipynb

You need to do the pip install after requesting tf1 and you need to use `--upgrade` because an old version of sb is installed by default on colab.

**Comment by araffin** [comment] 2020-05-21 07:11
Duplicate of https://github.com/hill-a/stable-baselines/issues/799 and https://github.com/hill-a/stable-baselines/issues/464

The root cause is the same, the error is different though.

**Closed** 2020-05-21 15:10 UTC
Labels: RTFM, colab, duplicate, question
