### ISSUE TITLE
How to retrain the saved model?

### ISSUE THREAD

**Issue by ZJP-c4cld** [hill-a/stable-baselines#739] opened 2020-03-12 03:37 UTC
I use command "model.save(save_path)" to save model and use command "model = train_model.load(save_path)" to restore the saved model. But I dont know how to continue training from the restored model rather than train from zero.

**Comment by araffin** [comment] 2020-03-12 08:41
Hello,
the answer is on the documentation.
Duplicate of #599

**Closed by araffin** 2020-03-12 08:41 UTC
Labels: RTFM, duplicate, question
