### ISSUE TITLE
Time-jumps during training 

### ISSUE THREAD

**Issue by meric-sakarya** [hill-a/stable-baselines#972] opened 2020-08-09 17:16 UTC
I am working on the Pendulum-v0 environment with the algorithm ppo2. I already managed to get the algorithm running with the suggested hyperparameters from the RL Baselines Zoo and achieved results. Furthermore, I am trying to use on top of the Monitor wrapper, a custom wrapper I made to change observations to images with the help of env.render("rgb_array") and the FrameStack wrapper to stack those frames. The problem is when I check the tensorboard graphs to evaluate the agent's progress, I find time jumps. Like the relative time for step 8.052k is 2 minutes and 31 seconds, and for step 8.196 this relative time increases to  3 minutes and 39 seconds. These time jumps occur approximately every 2 minutes and I think they are drastically slowing training. Between these time jumps the training speed is okay (150-200 steps per second).
 
The code:  

```import os
import time

import gym
from gym import Wrapper, spaces
import numpy as np
from numpy import zeros, newaxis
from gym.envs.classic_control import PendulumEnv
from stable_baselines.common.atari_wrappers import FrameStack

from stable_baselines.common.env_checker import check_env
from stable_baselines.sac.policies import CnnPolicy
from stable_baselines import PPO2
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.bench import Monitor

from skimage import color
from skimage import io
from skimage.transform import rescale, resize, downscale_local_mean
from skimage.color import rgb2gray
from skimage.filters import threshold_otsu

import tensorflow as tf


class RGBArrayAsObservationWrapper(Wrapper):
    """
    Use env.render(rgb_array) as observation
    rather than the observation environment provides
    """

    def __init__(self, env):
        # TODO this might not work before environment has been reset
        super(RGBArrayAsObservationWrapper, self).__init__(env)
        self.reset()
        # dummy_obs = env.render('rgb_array')
        # dummy_obs = resize(dummy_obs, (60, 60),
        #                   anti_aliasing=False)
        # dummy_obs = rgb2gray(dummy_obs)
        # dummy_obs = dummy_obs[:, :, newaxis]
        # Update observation space
        # TODO assign correct low and high
        self.observation_space = spaces.Box(low=0, high=1, shape=(60, 60, 1),
                                            dtype=np.float64)

    def reset(self, **kwargs):
        obs = self.env.reset(**kwargs)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (60, 60),
                     anti_aliasing=False)
        obs = rgb2gray(obs)
        # thresh = threshold_otsu(obs)
        obs = obs > 0.45
        obs = obs < 0.4
        obs = obs != 1
        obs = obs[:, :, newaxis]
        return obs

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (60, 60),
                     anti_aliasing=False)
        obs = rgb2gray(obs)
        # thresh = threshold_otsu(obs)
        obs = obs > 0.45
        obs = obs < 0.4
        obs = obs != 1

        obs = obs[:, :, newaxis]
        return obs, reward, done, info


# tensorboard --logdir=PPO2_IMG_PENDULUM:C:\Users\meric\OneDrive\Masaüstü\TUM\Thesis\Pycharm\pioneer\ppo2_pendulum_img_tensorboard --host localhost
tf.debugging.set_log_device_placement(True)
# Place tensors on the GPU

log_dir = "/tmp/gym/{}".format(int(time.time()))
os.makedirs(log_dir, exist_ok=True)

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

TEST_COUNT = 100

pendulum_env = gym.make('Pendulum-v0')
pendulum_env = Monitor(pendulum_env, log_dir, allow_early_resets=True)
pendulum_env = RGBArrayAsObservationWrapper(pendulum_env)
pendulum_env = FrameStack(pendulum_env, n_frames=2)
# check_env(pendulum_env, warn=True)

model = PPO2("CnnPolicy", n_steps=2048, nminibatches=32, lam=0.95, gamma=0.99,
             noptepochs=10, ent_coef=0.0, learning_rate=3e-4,
             cliprange=0.2, env=pendulum_env, verbose=1, tensorboard_log="./ppo2_pendulum_img_tensorboard/")
with tf.device('/GPU:0'):
    model.learn(total_timesteps=1_000_000, log_interval=10)
model.save("ppo2_pendulum_img")

```
What might be causing this problem and do you have any suggestions?

**System Info**
Describe the characteristic of your environment:
 * Describe how stable baselines was installed (pip, docker, source, ...): pip install stable-baselines[mpi]
 * GPU models and configuration: NVIDIA GTX 1050
 * Python version: 3.7
 * Tensorflow version: 1.15

**Comment by Miffyli** [comment] 2020-08-10 09:25
I am not quite I understand what you mean. Do you mean the training seems to stop every ~2 minutes for two-to-three minutes? 

Looking at the code I do not see bigger issues. However I assume the gym.render is not the fastest thing ever and you collect a reasonable amount of data (2048 steps), so I think the training steps will take some time and such behaviour is to be expected. I can not say why it is slowing down, though.

**Comment by meric-sakarya** [comment] 2020-08-10 10:22
Yes you understood right. Is there a way to just get the rgb-array without actually rendering?

**Comment by Miffyli** [comment] 2020-08-10 10:26
I do not think so, but that escapes outside stable-baselines issues. I suggest you try with smaller n_step count, e.g. `n_steps=256`. If the "stops" happen more frequently but are shorter, then this was the issue. And if so, this is expected behaviour as it can take some time to compute over the batch of data you have.

**Comment by meric-sakarya** [comment] 2020-08-10 12:37
You were right now they are more frequent but shorter. Is there a way to avoid this?

**Comment by Miffyli** [comment] 2020-08-10 12:50
Nope, that is simply the computation time required to train the network. I am not sure why it would slow down the further you go, though.

In any case, this does not seem to be an issue with stable-baselines, so you may close the issue.

**Comment by meric-sakarya** [comment] 2020-08-10 12:53
The training does not get slowed any further, but do you have an explanation for this. 
![2020-08-10 (4)](https://user-images.githubusercontent.com/38434300/89784613-40707a80-db19-11ea-959d-4267e4897e21.png)

**Comment by Miffyli** [comment] 2020-08-10 12:56
This goes to the "tuning RL parameters to get good results" territory, and it can be hard to pinpoint what the issue is exactly (we do not provide tech-support on that regard). I recommend checking docs for rl-tips and checking other issues. I'd personally first play around with `ent_coef`, perhaps increase it a little, but this is just a very wild guess.

**Closed by Miffyli** 2020-08-10 12:56 UTC
Labels: custom gym env, question
