### ISSUE TITLE
Tensorflow Deprecation Warnings

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#590] opened 2019-11-29 12:46 UTC
I get a bunch of tensorflow deprecation warnings when running PPO2 (haven't tried with other algorithms).

```
WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/tf_util.py:57: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/tf_util.py:66: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/policies.py:115: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/policies.py:562: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f00e3f98278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f00e3f98278>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/a2c/utils.py:156: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f00e03c1a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f00e03c1a58>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py:193: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py:209: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py:245: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.
```

I installed stable-baselines by `pip3 install stable-baselines` and tensorflow by `pip3 install tensorflow`.

```
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
stable-baselines==2.8.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0

```

**Comment by araffin** [comment] 2019-11-29 12:51
Hello,

Duplicate of #574 and  #298, will be solved with v3.0.

**Closed by araffin** 2019-11-29 12:51 UTC
Labels: duplicate
