### ISSUE TITLE
In PPO2 implementation, why normalize advantage for each batch?

### ISSUE THREAD

**Issue by denyHell** [hill-a/stable-baselines#697] opened 2020-02-19 19:04 UTC
I thought we were supposed to use adv as a guide to optimizing the policy (i.e. assign higher probability to actions that result in high advantage...). Wouldn't subtracting mean from the advantage diminish such effect?

**Comment by Miffyli** [comment] 2020-02-19 20:43
If the values used in training are too large or small, they will make learning unstable. In other words, if the variance of advantages is high, it can break the learning. Subtracting the mean reduces the variance and stabilizes learning, and it still retains the convergence properties. 

For further info, see the [material linked in docs](https://stable-baselines.readthedocs.io/en/master/guide/rl.html)

**Comment by araffin** [comment] 2020-02-19 20:59
Duplicate of https://github.com/hill-a/stable-baselines/issues/638

This is a common (unfortunately) undocumented trick.

**Closed by araffin** 2020-02-19 20:59 UTC
Labels: duplicate, question

**Comment by denyHell** [comment] 2020-02-19 21:33
thanks guys! 
the downside of this trick is that a batch of positive advs will have the similar effect as a batch of negative advs which is not what we want. Will try to compare results with/without subtracting the mean to see if there is any difference..
