### ISSUE TITLE
Tensorboard plotting in PPO2 is broken

### ISSUE THREAD

**Issue by drozzy** [hill-a/stable-baselines#518] opened 2019-10-23 15:36 UTC
When I use tensorboard for PPO2 training, the reward plot is really messed up:

![Screen Shot 2019-10-23 at 11 35 21 AM](https://user-images.githubusercontent.com/140710/67409950-4ea0da80-f589-11e9-87c2-cfca7fb6d2d9.png)

**Comment by Miffyli** [comment] 2019-10-23 15:41
Can you share a minimal code to reproduce this?

**Comment by araffin** [comment] 2019-10-23 16:49
Duplicate of #143

**Closed by araffin** 2019-10-23 16:49 UTC
Labels: duplicate
