### ISSUE TITLE
[question] Defining env with not bounded state

### ISSUE THREAD

**Issue by alejodosr** [hill-a/stable-baselines#824] opened 2020-04-24 10:31 UTC
Hi,

I am working with a custom environment where the state boundaries are not known (they are generated based on an external lstm internal state and can oscillate a lot). 

In order to set the environment boundaries with `spaces.Box(low=..., high=..., shape=..., dtype=np.float32)`, I see three options:

- Run the data for a certain period of time, find a local max and min, and normalize the state based on those values (it is not assured to get values higher than 1 or lower than 0).
- Define huge boundaries so you assure it is likely to be within the limits.
- Not defining the boundaries?

What is the recommendation in this case?
Thanks in advance.

**Comment by araffin** [comment] 2020-04-24 12:50
Duplicate of https://github.com/hill-a/stable-baselines/issues/820

(there are also other issues related to that if you search more)

**Comment by alejodosr** [comment] 2020-04-24 13:30
Sorry for the duplicate, did not read enough

**Closed** 2020-04-25 10:02 UTC
Labels: duplicate, question
