### ISSUE TITLE
Impala - Multi-agent [feature request]

### ISSUE THREAD

**Issue by Ujwal2910** [hill-a/stable-baselines#885] opened 2020-06-08 07:57 UTC
It would be really helpful if Impala or any distributed RL architectures for Multi-agent behaviour could also be added to the list of algorithms in stable-baselines. 

Thank you.

**Comment by araffin** [comment] 2020-06-08 08:27
>Multi-agent behaviour

Duplicate of #423 

>Impala or any distributed RL architectures

I did not have time to read carefully that paper yet but it seems like a big change to SB architecture.

**Comment by Ujwal2910** [comment] 2020-06-08 08:35
Any MA algorithm addition to SB would really help a lot since that is the only feature missing here. 
Any of these would really help in the rapid development of MA architectures and training:
1) Async PPO2
2) Distribute Impala
3) Policy - Impala CNN and Graph CNN
4) Global reward sharing feature between agents ->  similar to Dota bots developed by Openai where they had a teamwork parameter for reward sharing and cooperation.

I am also willing to help if it can be of any help. 

Perhaps addition of Algos using https://github.com/PettingZoo-Team/PettingZoo would be a great option

**Comment by Miffyli** [comment] 2020-06-08 08:48
These would indeed be big changes to the stable-baselines architecture, especially for this TF version. We could consider these as v1.2 and above features for stable-baselines3. Asynchronous running of the environments is useful if `reset`s take million years (like Minecraft MineRL), but to make good use of them requires good amount of optimizations and support for these algorithms.

**Comment by justinkterry** [comment] 2020-06-22 23:25
Of relevance to this issue: https://github.com/PettingZoo-Team/PettingZoo

**Comment by araffin** [comment] 2020-06-23 08:05
Closing this in favor of https://github.com/DLR-RM/stable-baselines3/issues/69

**Closed by araffin** 2020-06-23 08:05 UTC
Labels: duplicate, enhancement
