### ISSUE TITLE
can any of the baseline can be used for chess? [question]

### ISSUE THREAD

**Issue by Unimax** [hill-a/stable-baselines#695] opened 2020-02-19 06:49 UTC
can I use any of the baselines for a game like chess with either a custom env based on python-chess or https://github.com/genyrosk/gym-chess (i tried cannot use this directly)

i was trying to create a custom env but that i got stuck as who will play as an opponent and also there is only one reward.

Note: I am not trying to make the world's best chess ai.

**Comment by Miffyli** [comment] 2020-02-19 10:11
Yes, you can use stable-baselines to play chess: as long the environment provides correct API, then you can train agents there. Like you said the issue is "who is the opponent" and "what is the reward". You could have a fixed opponent, or use self-play like setup where the opponent is one of the previous versions of the agent being trained. You could do this by e.g. saving the model being trained periodically, and in the environment code create a new agent with `load()` method, that selects the actions of the other player.

But, this is not a place for help like this (more for issues/problems/questions specifically for stable-baselines).

**Comment by araffin** [comment] 2020-02-19 10:47
Related: #181

**Comment by araffin** [comment] 2020-02-19 10:49
I will close this issue because I feel it is a duplicate of the two issues mentioned above.

**Closed by araffin** 2020-02-19 10:49 UTC
Labels: No tech support, custom gym env, duplicate, question
