### ISSUE TITLE
How to auto tune hyperparameters in stable baselines?

### ISSUE THREAD

**Issue by sophiagu** [hill-a/stable-baselines#971] opened 2020-08-08 03:44 UTC
Hi everyone,

I'm using stable baselines agents for a custom problem. Hence I need to tune the agent hyperparameters to that specific problem. The zoo example seems to be using the original baselines command line for [optimizing the hyperparameters](https://github.com/araffin/rl-baselines-zoo#hyperparameter-tuning). But if I want to use [the stable baselines way of training](https://stable-baselines.readthedocs.io/en/master/modules/ppo2.html#example), how can I auto tune the hyperparameters?

Thanks,
Sophia

**Comment by sophiagu** [comment] 2020-08-08 03:51
Ohh I found zoo is actually using [Optuna](https://optuna.org/) for hyperparameters tuning. I guess the real problem is how to combine the stable baselines code with Optuna:
```
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    return (x - 2) ** 2

study = optuna.create_study()
study.optimize(objective, n_trials=100)

study.best_params
```

**Comment by araffin** [comment] 2020-08-08 17:53
Duplicate of https://github.com/araffin/rl-baselines-zoo/issues/29

**Closed by araffin** 2020-08-08 17:53 UTC
Labels: duplicate, question
