### ISSUE TITLE
Observation with multiple type of gym.spaces

### ISSUE THREAD

**Issue by giorgionicola** [hill-a/stable-baselines#313] opened 2019-05-07 12:28 UTC
Hi, I am wondering if DDPG or other algorithms implemented are able to handle an observation space that is partially Box (e.g. joints position/velocity) and partially Binary/Discrete.
Thanks

**Comment by araffin** [comment] 2019-05-07 12:31
Hello,
I think your question is a duplicate of #133 and is already documented (no support yet).

**Closed by araffin** 2019-05-07 12:31 UTC
Labels: RTFM, duplicate
