### ISSUE TITLE
Numerous TF warnings when running SAC from source

### ISSUE THREAD

**Issue by Antymon** [hill-a/stable-baselines#574] opened 2019-11-21 16:09 UTC
**Describe the bug**
When running SAC I get flooded with following warnings (possibly for each layer created):

WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc4e447c518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc4e447c518>>: AssertionError: Bad argument number for Name: 3, expecting 4

Are those safe to ignore, or? Why are those appearing on presumably legit code?

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: source
 * GPU models and configuration: no GPU
 * Python version: 3.6.8 
 * Tensorflow version 1.14
 * Versions of any other relevant libraries: Ubuntu 18.04 LTS

**Comment by araffin** [comment] 2019-11-21 17:02
Duplicate of #298 

>Are those safe to ignore, or? Why are those appearing on presumably legit code?

I remember having those (but I can't remember which setting exactly)  but you can normally ignore those.

Again, should be closed by #366 when v3.x is out.

**Comment by araffin** [comment] 2019-11-28 19:35
Closing this in favor of #298

**Closed by araffin** 2019-11-28 19:35 UTC
Labels: duplicate, question
