### ISSUE TITLE
unused of gpu

### ISSUE THREAD

**Issue by 980202006** [hill-a/stable-baselines#401] opened 2019-07-07 18:17 UTC
Hi，
My computer can't use GPU when running the algorithm of baselines, CPU works normally, but my tensorflow is the installed GPU version.
Can you tell me the possible reasons?

**Comment by araffin** [comment] 2019-07-07 19:46
Hello,
please fill up the issue template. Seems like a duplicate of #308

**Closed** 2019-07-18 17:59 UTC
Labels: more information needed, question
