### ISSUE TITLE
 ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by nachovoss** [hill-a/stable-baselines#393] opened 2019-06-30 00:45 UTC
Hey guys I'm getting this error when adapting a DummyVecEnv code that worked fine to SubprocVecEnv

any help would be much appreciated

Traceback (most recent call last):
  File "optimize.py", line 13, in <module>
    render_trained_model=True)
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\RLTrader.py", line 230, in train
    self.test(model_epoch, should_render=render_trained_model)
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\RLTrader.py", line 260, in test
    test_env.render(mode='system')
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 132, in render
    bigimg = tile_images(imgs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\tile_images.py", line 15, in tile_images
    n_images, height, width, n_channels = img_nhwc.shape
ValueError: not enough values to unpack (expected 4, got 1)

(base) C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL>

GPU = 1060 
CPU = i5 7600
Ram = 16gb

**Comment by araffin** [comment] 2019-06-30 06:40
Hello,

Please fill up the issue template.

**Comment by nachovoss** [comment] 2019-06-30 17:33
hey mate sorry  sorry here are the functions  the trace back error is calling


  def test(self, model_epoch: int = 0, should_render: bool = False):
        env_params = self.get_env_params()

        train_len = int(self.test_set_percentage * len(self.feature_df))
        test_df = self.feature_df[train_len:]

        test_env = SubprocVecEnv(
            [lambda: BitcoinTradingEnv(test_df, i, **env_params) for i in range(3)])

        model_path = path.join(
            'data', 'agents', f'{self.study_name}__{model_epoch}.pkl')
        model = self.Model.load(model_path, env=test_env)

        self.logger.info(
            f'Testing model ({self.study_name}__{model_epoch})')

        obs, done, rewards = test_env.reset(), False, []
        
        while not done:
            action, _states = model.predict(obs)
            obs, reward, done, _ = test_env.step(action)

            rewards.append(reward)
            
            if should_render:
#LINE260 #  test_env.render(mode='system')

        self.logger.info(
            f'Finished testing model ({self.study_name}__{model_epoch}): ${"{:.2f}".format(np.mean(rewards))}')

-----------------------------------
 def train(self, n_epochs: int = 1, iters_per_epoch: int = 1, test_trained_model: bool = False, render_trained_model: bool = False):
        env_params = self.get_env_params()

        train_len = int(self.test_set_percentage * len(self.feature_df))
        train_df = self.feature_df[:train_len]

        train_env = SubprocVecEnv(
            [lambda: BitcoinTradingEnv(train_df, i, **env_params) for i in range(3)])

        model_params = self.get_model_params()

        #model = self.Model(self.Policy, train_env, verbose=self.model_verbose, nminibatches=self.nminibatches,
                           #tensorboard_log=self.tensorboard_path, **model_params)

        model = self.Model(self.Policy, train_env, verbose=self.model_verbose, nminibatches=self.nminibatches, **model_params)

        self.logger.info(f'Training for {n_epochs} epochs')

        n_timesteps = len(train_df) * iters_per_epoch

        for model_epoch in range(0, n_epochs):
            self.logger.info(
                f'[{model_epoch}] Training for: {n_timesteps} time steps')

            model.learn(total_timesteps=n_timesteps)

            model_path = path.join(
                'data', 'agents', f'{self.study_name}__{model_epoch}.pkl')
            model.save(model_path)
            

            if test_trained_model:
#LINE230#    self.test(model_epoch, should_render=render_trained_model)
                

        self.logger.info(f'Trained {n_epochs} models')

**Comment by araffin** [comment] 2019-06-30 17:52
This is not the issue template...

**Comment by nachovoss** [comment] 2019-06-30 19:04
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.

**Describe the bug**
A clear and concise description of what the bug is.
When adapting functions to work with SubprocVecEnv from DummyVecEnv they stop working
**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.
def test(self, model_epoch: int = 0, should_render: bool = False):
env_params = self.get_env_params()

    train_len = int(self.test_set_percentage * len(self.feature_df))
    test_df = self.feature_df[train_len:]

    test_env = SubprocVecEnv(
        [lambda: BitcoinTradingEnv(test_df, i, **env_params) for i in range(3)])

    model_path = path.join(
        'data', 'agents', f'{self.study_name}__{model_epoch}.pkl')
    model = self.Model.load(model_path, env=test_env)

    self.logger.info(
        f'Testing model ({self.study_name}__{model_epoch})')

    obs, done, rewards = test_env.reset(), False, []
    
    while not done:
        action, _states = model.predict(obs)
        obs, reward, done, _ = test_env.step(action)

        rewards.append(reward)
        
        if should_render:
#LINE260 # test_env.render(mode='system')

    self.logger.info(
        f'Finished testing model ({self.study_name}__{model_epoch}): ${"{:.2f}".format(np.mean(rewards))}')
def train(self, n_epochs: int = 1, iters_per_epoch: int = 1, test_trained_model: bool = False, render_trained_model: bool = False):
env_params = self.get_env_params()

    train_len = int(self.test_set_percentage * len(self.feature_df))
    train_df = self.feature_df[:train_len]

    train_env = SubprocVecEnv(
        [lambda: BitcoinTradingEnv(train_df, i, **env_params) for i in range(3)])

    model_params = self.get_model_params()

    #model = self.Model(self.Policy, train_env, verbose=self.model_verbose, nminibatches=self.nminibatches,
                       #tensorboard_log=self.tensorboard_path, **model_params)

    model = self.Model(self.Policy, train_env, verbose=self.model_verbose, nminibatches=self.nminibatches, **model_params)

    self.logger.info(f'Training for {n_epochs} epochs')

    n_timesteps = len(train_df) * iters_per_epoch

    for model_epoch in range(0, n_epochs):
        self.logger.info(
            f'[{model_epoch}] Training for: {n_timesteps} time steps')

        model.learn(total_timesteps=n_timesteps)

        model_path = path.join(
            'data', 'agents', f'{self.study_name}__{model_epoch}.pkl')
        model.save(model_path)
        

        if test_trained_model:
#LINE230# self.test(model_epoch, should_render=render_trained_model)

    self.logger.info(f'Trained {n_epochs} models')
```python
from stable_baselines import ...

```

```bash
Traceback (most recent call last): File ...

```Traceback (most recent call last):
File "optimize.py", line 13, in 
render_trained_model=True)
File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\RLTrader.py", line 230, in train
self.test(model_epoch, should_render=render_trained_model)
File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\RLTrader.py", line 260, in test
test_env.render(mode='system')
File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 132, in render
bigimg = tile_images(imgs)
File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\tile_images.py", line 15, in tile_images
n_images, height, width, n_channels = img_nhwc.shape
ValueError: not enough values to unpack (expected 4, got 1)

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
  Conda base
 * GPU models and configuration
   gtx 1060 3gb
 * Python version
   3.7
 * Tensorflow version
 1.13.1
 * Versions of any other relevant libraries
  numpy
pandas
sklearn
matplotlib
gym
optuna
ta
statsmodels==0.10.0rc2
empyrical
tensorflow-gpu
**Additional context**
Add any other context about the problem here.
 if you need the hole file i can attach
![Anotación 2019-06-29 203415](https://user-images.githubusercontent.com/38444147/60400773-fe84af00-9b78-11e9-8142-1668a9f46f90.png)
![Captura](https://user-images.githubusercontent.com/38444147/60400774-fe84af00-9b78-11e9-8f69-c522d7799599.PNG)
![Captura2](https://user-images.githubusercontent.com/38444147/60400775-fe84af00-9b78-11e9-87d6-14b20fc826ff.PNG)
![Captura3](https://user-images.githubusercontent.com/38444147/60400776-ff1d4580-9b78-11e9-9b7a-1ccac57925e6.PNG)
![Captura4](https://user-images.githubusercontent.com/38444147/60400777-ff1d4580-9b78-11e9-820a-f17f00058695.PNG)
![Captura5](https://user-images.githubusercontent.com/38444147/60400778-ff1d4580-9b78-11e9-93dd-ad24aec568fa.PNG)
![Captura8](https://user-images.githubusercontent.com/38444147/60400779-ffb5dc00-9b78-11e9-8b3a-d90e3fe62761.PNG)
![Capturaw](https://user-images.githubusercontent.com/38444147/60400780-ffb5dc00-9b78-11e9-80ef-3ca74de26708.PNG)

**Comment by nachovoss** [comment] 2019-06-30 19:04
![Anotación 2019-06-29 203415](https://user-images.githubusercontent.com/38444147/60400904-a8187000-9b7a-11e9-8db4-93b99cfc4e5f.png)
![Captura](https://user-images.githubusercontent.com/38444147/60400905-a8b10680-9b7a-11e9-8d0c-af017a8770a9.PNG)
![Captura2](https://user-images.githubusercontent.com/38444147/60400906-a8b10680-9b7a-11e9-8322-aa88ed8c89a0.PNG)
![Captura3](https://user-images.githubusercontent.com/38444147/60400907-a8b10680-9b7a-11e9-86a5-b46992526bfe.PNG)
![Captura4](https://user-images.githubusercontent.com/38444147/60400908-a8b10680-9b7a-11e9-840f-07ed850d4bc7.PNG)
![Captura5](https://user-images.githubusercontent.com/38444147/60400909-a8b10680-9b7a-11e9-9f5e-59e7ed67d81b.PNG)
![Captura8](https://user-images.githubusercontent.com/38444147/60400910-a9499d00-9b7a-11e9-94d9-fe054a895dd9.PNG)
![Capturaw](https://user-images.githubusercontent.com/38444147/60400911-a9499d00-9b7a-11e9-90de-69e4a37ec4ef.PNG)

**Comment by nachovoss** [comment] 2019-06-30 19:05
closed by accident

**Comment by nachovoss** [comment] 2019-06-30 19:24
2019-06-30 21:11:04,277 - lib.RLTrader - initialize_optuna - DEBUG - Initialized Optuna:
  2019-06-30 21:11:04,388 - lib.RLTrader - initialize_optuna - DEBUG - Best reward in (76) trials: -1969007.5
  2019-06-30 21:11:04,389 - lib.RLTrader - __init__ - DEBUG - Initialize RLTrader: PPO2__MlpLnLstmPolicy__sortino
Process SpawnProcess-6:
Process SpawnProcess-5:
Process SpawnProcess-4:
Traceback (most recent call last):
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 23, in _worker
    observation = env.reset()
Traceback (most recent call last):
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 159, in reset
    return self._next_observation()
Traceback (most recent call last):
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 61, in _next_observation
    model_fit = forecast_model.fit(method='bfgs', disp=False)
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 445, in fit
    start_params = self.start_params
  File "C:\Users\Nacho\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 23, in _worker
    observation = env.reset()
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 938, in start_params
    self.polynomial_ma, self.k_trend, trend_data
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 23, in _worker
    observation = env.reset()
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 159, in reset
    return self._next_observation()
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 860, in _conditional_sum_squares
    X = np.c_[X, lagmat(endog, k_ar)[r:, cols]]
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 159, in reset
    return self._next_observation()
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 61, in _next_observation
    model_fit = forecast_model.fit(method='bfgs', disp=False)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py", line 406, in lagmat
    raise ValueError("maxlag should be < nobs")
  File "C:\Users\Nacho\Desktop\bots\traders\Bitcoin-Trader-RL\lib\env\BitcoinTradingEnv.py", line 61, in _next_observation
    model_fit = forecast_model.fit(method='bfgs', disp=False)
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 445, in fit
    start_params = self.start_params
ValueError: maxlag should be < nobs
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 445, in fit
    start_params = self.start_params
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 938, in start_params
    self.polynomial_ma, self.k_trend, trend_data
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 938, in start_params
    self.polynomial_ma, self.k_trend, trend_data
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 860, in _conditional_sum_squares
    X = np.c_[X, lagmat(endog, k_ar)[r:, cols]]
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 860, in _conditional_sum_squares
    X = np.c_[X, lagmat(endog, k_ar)[r:, cols]]
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py", line 406, in lagmat
    raise ValueError("maxlag should be < nobs")
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py", line 406, in lagmat
    raise ValueError("maxlag should be < nobs")
ValueError: maxlag should be < nobs
ValueError: maxlag should be < nobs

**Comment by araffin** [comment] 2019-06-30 20:21
Please use proper code formatting (cf link in the readme).

It seems your problem is related to the trader rl repo (the env and scripts you are using), not stable baselines, unless you can provide a minimal code that breaks without relying on that resource.
So i would advise you to open an issue on that repo.

**Comment by rporotti** [comment] 2019-07-01 13:03
Hi, I think I have the same problem, working with SubprocVecEnv and the render function, for a custom Environment. Basically, when I have a code like this:

```python
import gym
import numpy as np
from stable_baselines.common.policies import MlpLstmPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines import PPO2

class Env(gym.Env):

    def __init__(self):
        self.action_space = gym.spaces.Box(low=1, high=1, shape=(1,), dtype=np.float32)
        self.observation_space = gym.spaces.Box(low=1, high=1, shape=(1,), dtype=np.float32)

    def render(self, mode="human"):
        True

env = SubprocVecEnv([lambda: Env() for i in range(2)])
model = PPO2(MlpLstmPolicy, env, nminibatches=2)

env.render()
```
I receive the error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-e20028144b9d> in <module>
     18 
     19 
---> 20 env.render()

~/.local/lib/python3.5/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py in render(self, mode, *args, **kwargs)
    130         imgs = [pipe.recv() for pipe in self.remotes]
    131         # Create a big image by tiling images from subprocesses
--> 132         bigimg = tile_images(imgs)
    133         if mode == 'human':
    134             import cv2

~/.local/lib/python3.5/site-packages/stable_baselines/common/tile_images.py in tile_images(img_nhwc)
     13     """
     14     img_nhwc = np.asarray(img_nhwc)
---> 15     n_images, height, width, n_channels = img_nhwc.shape
     16     # new_height was named H before
     17     new_height = int(np.ceil(np.sqrt(n_images)))

ValueError: not enough values to unpack (expected 4, got 1)
```
The same holds if I change the policy. The other functions (e.g. reset(), step() and so on) work perfectly fine.


**System Info**
 * Tensorflow version: 1.14.0
 * Stable-baselines version: 2.6.0

**Comment by araffin** [comment] 2019-07-01 13:14
@rporotti  what do you except from the render function?

Usually there are two modes for the render method: "human" and "rgb_array", the first one uses the second one with VecEnv (because of subprocesses, the GUI of the "human" mode cannot be displayed directly).
Looking at your custom env, your observation is definitely not an image, but I don't know what your render method does, and that's where the error comes from.

**Comment by rporotti** [comment] 2019-07-02 06:37
This was just a MWE to reproduce the error. In my custom env, I would just like to save an image with matplotlib (pyplot.savefig() ), and I don't want to visualize it during runtime. Something like:
```python
class Env(gym.Env):

    def step(self, u):
        self.actions.append(u)
    def render(self, mode="human"):
        plt.plot(u)
        plt.savefig(u)

```
When the environment is not parallelized, everything works fine. Is there a way to do such thing?

**Comment by araffin** [comment] 2019-07-02 07:45
I would advise you to create a method that is not called render for that, and use the `env_method` (cf documentation) of the vec env to call that method.

**Comment by rporotti** [comment] 2019-07-02 08:51
Great, thank you very much.
I think I still have some problems in calling the ```env_method``` function:
```python
class Env(gym.Env):
    def plot(self, something):
        True

env = SubprocVecEnv([lambda: Env() for i in range(2)])
env.env_method(method_name=env.plot())
```
outputs
```
AttributeError: 'SubprocVecEnv' object has no attribute 'plot'
```
I tried many alternatives but nothing seems to works. Thank you for your patience, I'm not that advanced in python programming.

**Comment by araffin** [comment] 2019-07-02 11:19
Ok, I will close the issue then, as it does not seem to be directly related to SB and a solution has been proposed.

**Closed by araffin** 2019-07-02 11:19 UTC
Labels: custom gym env, more information needed, windows
