### ISSUE TITLE
Does set_global seed work? [question]

### ISSUE THREAD

**Issue by HDClark94** [hill-a/stable-baselines#285] opened 2019-04-23 10:23 UTC
Hello,

I've been playing around with the example code you've provided on the docs and noticed the global seed example in the cart pole environment isn't reproducing the same results on successive runs. 

Is this to be expected?

I've tested this with a fresh install of gym and stable-baselines. 

Thanks

**Code example**
```python
import gym
import numpy as np

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines.common import set_global_seeds
from stable_baselines import ACKTR

def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_global_seeds(seed)
    return _init

env_id = "CartPole-v1"
num_cpu = 4  # Number of processes to use
# Create the vectorized environment
env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])

model = ACKTR(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)

obs = env.reset()
for _ in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

```

**Comment by hill-a** [comment] 2019-04-23 10:48
Hey,

Unfortunatly, some GPU operations are non deterministic on tensorflow (https://github.com/tensorflow/tensorflow/issues/2732). And since we are using those operations we cannot assure perfect reproducibility of a given run.

We should mention this in the doc when using `set_global_seeds()`, dont you think @araffin ?

**Comment by araffin** [comment] 2019-04-23 11:07
Hello,
Currently `set_global_seeds()` only work partially: the initial weights will be the same, the initial state of the environment will be the same (when using `env.seed`) but because of tensorflow, you will get different results.

I have been a bit working on that on the `deterministic-fix` branch (see [here](https://github.com/hill-a/stable-baselines/compare/master...hill-a:deterministic-fix) for what I did, it worked for PPO2, A2C and some others algos but not all)

>We should mention this in the doc when using set_global_seeds(), dont you think @araffin ?

yes, good point.

I think this issue may be a duplicate of https://github.com/hill-a/stable-baselines/issues/145

**Comment by greg234234** [comment] 2019-05-22 13:30
> I have been a bit working on that on the `deterministic-fix` branch (see [here](https://github.com/hill-a/stable-baselines/compare/master...hill-a:deterministic-fix) for what I did, it worked for PPO2, A2C and some others algos but not all)
> 
Hi, great compliments to you all and this work.  I'm testing the deterministic-fix in Colab with little success. I pasted the code of test_deterministic.py into a cell, along with: test_deterministic_training_common(ACER)     

This returns:
 
`[[array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([1]), array([0]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([1]), array([0]), array([1]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([1]), array([1]), array([0]), array([0]), array([0]), array([1]), array([1]), array([1]), array([1]), array([1]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([0]), array([1]), array([0]), array([1]), array([0])], [array([0]), array([1]), array([0]), array([1]), array([1]), array([0]), array([1]), array([1]), array([1]), array([0]), array([1]), array([1]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([0]), array([0]), array([1]), array([1]), array([0]), array([1]), array([1]), array([0]), array([0]), array([1]), array([1]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([0]), array([0]), array([1]), array([0]), array([1]), array([0]), array([1]), array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([1]), array([1]), array([1]), array([1]), array([0]), array([0]), array([0]), array([0]), array([0]), array([1]), array([1]), array([1]), array([1]), array([1]), array([1]), array([0]), array([0]), array([0]), array([1]), array([1])]]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-42-8e9c011605e2> in <module>()
     99 
    100 
--> 101 test_deterministic_training_common(ACER)

<ipython-input-42-8e9c011605e2> in test_deterministic_training_common(algo)
     45             results[i].append(action)
     46             rewards[i].append(reward)
---> 47     assert sum(results[0]) == sum(results[1]), print(results)
     48     assert sum(rewards[0]) == sum(rewards[1]), print(rewards)
     49 

AssertionError: None`

**Comment by araffin** [comment] 2019-05-22 14:02
Can you please send the colab link? (and it seems the assert were not done properly)
Also, I should update this branch which is a bit far behind master now.

**Comment by greg234234** [comment] 2019-05-22 15:53
Yes of course, here's a link https://colab.research.google.com/drive/1CLi0EhDZrLnrjGZaxeLuf4HK_VKcjDU6

I'm making a new cell to investigate the assert error

**Comment by araffin** [comment] 2019-05-22 16:28
Quick question : are you using a gpu with cuda? If so, you must use a cpu to have deterministic results.
In pytorch, there is a flag for cuda to make it deterministic, in tf i don t know.

**Comment by greg234234** [comment] 2019-05-22 17:00
@araffin Thanks for pointing me in the right direction

> Quick question : are you using a gpu with cuda? If so, you must use a cpu to have deterministic results.
Yes, I'm using gpu with cuda. To clarify, is training with GPU acceptable then using the CPU to evaluate the model?

**Comment by araffin** [comment] 2019-05-22 17:08
I meant this branch : https://github.com/hill-a/stable-baselines/tree/deterministic-fix (see link above in the discussion), there is a typo in my command.

>To clarify, is training with GPU acceptable then using the CPU to evaluate the model?

Yes but the training won't be deterministic.

**Comment by greg234234** [comment] 2019-05-22 17:26
Thanks!  Ok I see your point, so with cuda we're limited to CPU until TF is updated with fixes but GPUs that don't use cuda are confirmed as working?
   
Sorry for all the questions, I've been catching up with threads with stable-baselines, baselines, and tensorflow about the subject looking for answers.

**Comment by greg234234** [comment] 2019-05-25 00:50
Apologies because this could be expected behavior, but I wanted to test deterministic this way, as per your code, but with the loop placed after the model has been trained.  Should the model after being loaded perform the same on two evaluations?

**Closed** 2019-10-11 13:59 UTC
Labels: documentation, question
