### ISSUE TITLE
SubprocVecEnv: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by HongminWu** [hill-a/stable-baselines#798] opened 2020-04-13 10:15 UTC
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.

If your issue is related to a custom gym environment, please check it first using:

```python
from stable_baselines.common.env_checker import check_env

env = CustomEnv(arg1, ...)
# It will check your custom environment and output additional warnings if needed
check_env(env)
```

**Describe the bug**

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)
for both code and stack traces.

```python
from stable_baselines import ...

```

```bash
Traceback (most recent call last): File ...

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
 * GPU models and configuration
 * Python version
 * Tensorflow version
 * Versions of any other relevant libraries

**Additional context**

**Comment by araffin** [comment] 2020-04-13 11:35
Hello,
Please fill the issue template completely.
Sounds like a duplicate of https://github.com/hill-a/stable-baselines/issues/483

**Comment by HongminWu** [comment] 2020-04-14 02:03
Dear there,
problem solved. I will recall this query.
Thanks.
-----------------------------------------
Hongmin Wu, Post-doc
Project Leader of Robots Team
Guangdong Institute of Intelligent Manufacturing (GIIM)
Guangzhou, Guangdong, P.R.China 510006
WeChat: Homing20
Facebook: Hongmin Wu
Tel: 86+18819498204
E-mail: *hongminwu0120@gmail.com <hongminwu0120@gmail.com>,
hm.wu@giim.ac.cn <hm.wu@giim.ac.cn>*
Open Source: https://github.com/HongminWu

**Closed** 2020-04-14 02:08 UTC
Labels: duplicate, more information needed

**Comment by haonanhe** [comment] 2021-12-25 06:52
Hello, I'm facing the same problem now. And the solution mentioned in #483 which suggests `if __name__ == "__main__":` does not make any difference. Do you know how to solve it? @HongminWu @araffin

**Comment by Miffyli** [comment] 2021-12-27 12:35
@haonanhe Sounds like the issue is in your environment. If you are using a custom environment we can not provide much help / tech support with that. If the bug really stems from SB3, please open up a new issue.
