### ISSUE TITLE
SubprocVecEnv ImportError, sys.path change in SubprocVecEnv

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [hill-a/stable-baselines#920] opened 2020-07-02 21:31 UTC
So I have faced an issue which has been quite confusing for me and I try my best to describe it here. I am using SubprocVecEnv to instantiate a number of parallel environments, where the code can be summarized as the following:

```
import TheGymEnv 
env = SubprocVecEnv([TheGymEnv for i in range(1)])
```
The line for importing TheGymEnv will invoke an `__init__.py` file under the hood which which works fine. Then when the second line is executing, the same `__init__.py` file is called again, yet, with the error :
```
  File "/home/azerila/ws/src/pkgs_for_py3/geometry2/tf2_py/src/tf2_py/__init__.py", line 46, in <module>
   from ._tf2 import *
ImportError: cannot import name '_tf2'
```
the above` __init__.py` also has the following code, excluding its comments:
```
#! /usr/bin/python
from __future__ import absolute_import
from ._tf2 import *
```

Since this `__init__.py` is called two times, once during the `import TheGymEnv ` and once in executing `env = SubprocVecEnv(...` I put a few lines lines inside it like `print(os.environ["PYTHONPATH"])` to check its environemntal variables but for both times the same PYTHONPATH was printed. 

So I don't understand why one time this python file is executed with no problem and why the second time in SubprocVecEnv the above import error shows up. 

checking more about the `_tf2` which is used in this python file, it was directed to the following file.
`<module 'tf2_py._tf2' from '/home/azerila/ws/devel/lib/python3/dist-packages/tf2_py/_tf2.so'>
`

does anyone know what might be the source of this issue, and what I else I can check about that might give some clue?

**Comment by Miffyli** [comment] 2020-07-02 22:08
Please include the full source next time to the extent the issue can be replicated. This seems to go outside stable-baselines issues, and relates to the custom env used / TF2 / Python installation used, and these issues are for stable-baselines issues/suggestions rather than tech support. 

My wild guess is that TF2 does not like being imported many times from different processes like that, but I have no experience with it. Other things you want to check are the directories where the code resides when trying to import _tf2 etc. Unfortunately I do not have further ideas to give.

**Comment by a-z-e-r-i-l-a** [comment] 2020-07-03 11:42
So I noticed that the problem is the different sys.path that is used each time.

I have now a line before importing _tf2 which prints sys.path and the result is different between the first(before SubprocVecEnv) and the second time(inside SubprocVecEnv). Hardcoding the sys.path before import solves the problem but I wonder if there might be a better way. 

The problem was not however specific to TF2.

**Comment by Miffyli** [comment] 2020-07-03 11:54
This still does not sound like a stable-baselines/SubProcVecEnv issue, though. Sounds like something wonky with that specific Python installation. If you can provide a minimal code to reproduce the bug reliably on multiple machines (without tf2 or other special libraries), please share it. Otherwise you can close the issue.

**Closed** 2020-07-16 19:13 UTC
Labels: No tech support

**Comment by SammyRamone** [comment] 2021-04-28 07:23
If somebody is stumbling over this closed thread in future, here is the solution:
The problem is indeed the python path which is not correctly in the subprocesses that are created by the subprocVecEnv. This is not a stable-baselines (or stable-baselines3) issue but comes from catkin. You can fix this by replacing `sys_path.insert(0,p)` with `sys_path.append(p)` in the corresponding `__init__.py` of the build catkin package. This would be in this case `catkin_ws/devel/lib/python3/dist-packages/tf2_py/__init__.py`
The catkin maintainer team is already aware of this issue it may change this in the future.
