### ISSUE TITLE
PPO2 Tenseborad log : Tag was already used

### ISSUE THREAD

**Issue by riz0410** [hill-a/stable-baselines#1019] opened 2020-10-08 12:26 UTC
Hi
I am trying to run PPO2, but unable to do so, receiving the following errors:

**Code required for reproducing:**
from stable_baselines import PPO2
PPO2("MlpPolicy", "CartPole-v1", tensorboard_log="/tmp/test_v1", full_tensorboard_log=True,
...     verbose=1).learn(100000)

Creating environment from the given name, wrapped in a DummyVecEnv.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:58: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/tf_util.py:67: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/policies.py:115: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/policies.py:560: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/a2c/utils.py:156: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:194: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:205: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

INFO:tensorflow:Summary name model/pi_fc0/w:0 is illegal; using model/pi_fc0/w_0 instead.
INFO:tensorflow:Summary name model/pi_fc0/b:0 is illegal; using model/pi_fc0/b_0 instead.
INFO:tensorflow:Summary name model/vf_fc0/w:0 is illegal; using model/vf_fc0/w_0 instead.
INFO:tensorflow:Summary name model/vf_fc0/b:0 is illegal; using model/vf_fc0/b_0 instead.
INFO:tensorflow:Summary name model/pi_fc1/w:0 is illegal; using model/pi_fc1/w_0 instead.
INFO:tensorflow:Summary name model/pi_fc1/b:0 is illegal; using model/pi_fc1/b_0 instead.
INFO:tensorflow:Summary name model/vf_fc1/w:0 is illegal; using model/vf_fc1/w_0 instead.
INFO:tensorflow:Summary name model/vf_fc1/b:0 is illegal; using model/vf_fc1/b_0 instead.
INFO:tensorflow:Summary name model/vf/w:0 is illegal; using model/vf/w_0 instead.
INFO:tensorflow:Summary name model/vf/b:0 is illegal; using model/vf/b_0 instead.
INFO:tensorflow:Summary name model/pi/w:0 is illegal; using model/pi/w_0 instead.
INFO:tensorflow:Summary name model/pi/b:0 is illegal; using model/pi/b_0 instead.
INFO:tensorflow:Summary name model/q/w:0 is illegal; using model/q/w_0 instead.
INFO:tensorflow:Summary name model/q/b:0 is illegal; using model/q/b_0 instead.
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:210: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:246: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From /home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/common/base_class.py:1082: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

--------------------------------------
| approxkl           | 6.361204e-05  |
| clipfrac           | 0.0           |
| explained_variance | -0.00809      |
| fps                | 225           |
| n_updates          | 1             |
| policy_entropy     | 0.69307256    |
| policy_loss        | -0.0004277638 |
| serial_timesteps   | 128           |
| time_elapsed       | 2.62e-06      |
| total_timesteps    | 128           |
| value_loss         | 38.9179       |
--------------------------------------
--------------------------------------
| approxkl           | 3.1568145e-06 |
| clipfrac           | 0.0           |
| explained_variance | -0.0605       |
| fps                | 1696          |
| n_updates          | 2             |
| policy_entropy     | 0.6928721     |
| policy_loss        | 8.003204e-06  |
| serial_timesteps   | 256           |
| time_elapsed       | 0.569         |
| total_timesteps    | 256           |
| value_loss         | 30.389145     |
--------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 355, in learn
    update=timestep, cliprange_vf=cliprange_vf_now))
  File "/home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 294, in _train_step
    writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
  File "/home/iiitd/anaconda3/envs/myenv/lib/python3.7/site-packages/tensorflow/python/summary/writer/writer.py", line 264, in add_run_metadata
    **raise ValueError("The provided tag was already used for this event type")
ValueError: The provided tag was already used for this event type**

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed : using pip install stable-baselines
 * GPU models and configuration:  GeForce RTX 2070 
 * Python version: 3.7.6
 * Tensorflow version: 1.14.0
 * Versions of any other relevant libraries: NA

**Additional context**

**Comment by Miffyli** [comment] 2020-10-08 12:32
Duplicate of #472 and #827 and seems to be fixed by #822. 

Solution: Install stable-baselines from current master with `pip install git+https://github.com/hill-a/stable-baselines`.

**Closed by Miffyli** 2020-10-08 12:32 UTC

**Comment by riz0410** [comment] 2020-10-08 13:55
Hi Miffyli,

Thanks for the quick response, this solution worked for the predefined cartpole env. However, when I am running it for my custom env it is again giving me the same error after 2 loops. This custom environment is working fine with TRPO alg of stable baseline.

**code**

    # Create log dir
    logdir = get_latest_dir()

    with open(os.path.join(logdir, 'command.txt'), 'w') as f:
        json.dump(args.__dict__, f, indent=2)

    # Initialize environment
    register(
        id='foo-{}-v0'.format(args.num_users),
        entry_point='gym_foo.envs:FooEnv',
        kwargs={'numberOfNodes' : args.num_users, 'reqd':int(args.reqdata) },
    )
    env = gym.make('foo-{}-v0'.format(args.num_users,args.reqdata))
    check_env(env)
    env = Monitor(env, logdir, allow_early_resets=True)
    env = DummyVecEnv([lambda: env])
    

    if args.alg == 'TRPO':
        algo = TRPO
    elif args.alg == 'PPO2':
        algo = PPO2
    elif args.alg=='PPO1':
        algo = PPO1

    if args.mode == 'train':
        print ("Start Training... \nUsers: ", args.num_users, " Algo: ", args.alg, " \nTimesteps: ", args.num_steps, " Gamma: ", args.gamma)
        model = algo(MlpPolicy, env, gamma=args.gamma, verbose=1, tensorboard_log=logdir, full_tensorboard_log=True)
        # model = algo(MlpPolicy, env, gamma=args.gamma, verbose=1, tensorboard_log="/tmp/test_v1", full_tensorboard_log=True)
        model.learn(total_timesteps=args.num_steps)# callback=callback)
        model.save(os.path.join('./' + logdir, "{}_users_{}_timesteps_{}_gamma_{}".format(args.alg, args.num_users, args.num_steps,args.gamma)), cloudpickle=True)
        print ("saved")

def get_latest_dir():
    log_dir = "rl_logs/"
    folders = sorted(glob.glob(log_dir + '*'))
    if len(folders) == 0:
        log_dir = log_dir  + '1'
        os.makedirs(log_dir, exist_ok=True)
        return log_dir
    nums = []
    for f in folders:
        f = f.split('/')
        nums.append(int(f[1]))
    nums = sorted(nums)[::-1]
    last = nums[0]
    curr = str(last + 1)
    log_dir = os.path.join(log_dir, curr)
    os.makedirs(log_dir, exist_ok=True)
    return log_dir

    
    # env = gym.make('foo-{}-v0'.format(args.num_users,args.reqdata))
    writer = SummaryWriter(log_dir=logdir)
    if args.model_path == None:
        model = algo.load(os.path.join('./' + logdir,"{}_users_{}_timesteps_{}_gamma_{}".format(args.alg, args.num_users, args.num_steps,args.gamma)))
    else:
        model = algo.load(args.model_path)

    state = env.reset()




**command : python3.6 train_agent_2.py --num-users 5   --reqdata 100 --alg PPO2**

**output**
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
--------inti-----------------
/home/iiitd/.local/lib/python3.6/site-packages/stable_baselines/common/env_checker.py:202: UserWarning: Your observation has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector
  warnings.warn("Your observation has an unconventional shape (neither an image, nor a 1D vector). "
----------reset-----------------
reset end 5
Start Training... 
Users:  5  Algo:  PPO2  
Timesteps:  50000000  Gamma:  0.9
----------reset-----------------
reset end 5
--------------------------------------
| approxkl           | 8.14384e-05   |
| clipfrac           | 0.0           |
| explained_variance | -0.000188     |
| fps                | 122           |
| n_updates          | 1             |
| policy_entropy     | 8.95859       |
| policy_loss        | -0.0017605671 |
| serial_timesteps   | 128           |
| time_elapsed       | 2.62e-06      |
| total_timesteps    | 128           |
| value_loss         | 3045646.5     |
--------------------------------------
--------------------------------------
| approxkl           | 0.0009414729  |
| clipfrac           | 0.0           |
| explained_variance | 0.000156      |
| fps                | 200           |
| n_updates          | 2             |
| policy_entropy     | 8.955442      |
| policy_loss        | -0.0077297385 |
| serial_timesteps   | 256           |
| time_elapsed       | 1.05          |
| total_timesteps    | 256           |
| value_loss         | 4293350.5     |
--------------------------------------
Traceback (most recent call last):
  File "train_agent_2.py", line 273, in <module>
    model.learn(total_timesteps=args.num_steps)# callback=callback)
  File "/home/iiitd/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 355, in learn
    update=timestep, cliprange_vf=cliprange_vf_now))
  File "/home/iiitd/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 294, in _train_step
    writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
  **File "/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 262, in add_run_metadata
    raise ValueError("The provided tag was already used for this event type")
ValueError: The provided tag was already used for this event type**


Could you pls tell me what I might be doing wrong? does this have to do something with logdir variable?

Your help is highly appericated
TIA

**Comment by Miffyli** [comment] 2020-10-08 13:59
The error you are looking for is higher up: 

> UserWarning: Your observation has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector

See the results from `check_env`. Seems like your environment is providing odd-shaped observations.

**Comment by riz0410** [comment] 2020-10-09 06:06
@Miffyli ,

Thank you for your response, I have corrected the warning of observation space. Now check env does not give any error. Still I am unable to run PPO2, whereas TRPO and PPO1 are working fine on the same env. PPO2 is terminating exactly after two iterations everytime. Could you pls guide me where should I possibly  look into for this? as previously other users have reported similar issues  
https://github.com/hill-a/stable-baselines/issues/472
https://github.com/hill-a/stable-baselines/issues/827
https://github.com/hill-a/stable-baselines/pull/822


Current output
python3.6 train_agent_2.py --num-users 5   --reqdata 100 --alg PPO2
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
--------inti-----------------
obs sapce Box(35,)
(10,)
----------reset-----------------
reset end 5
Start Training... 
Users:  5  Algo:  PPO2  
Timesteps:  50000000  Gamma:  0.9
----------reset-----------------
reset end 5
--------------------------------------
| approxkl           | 4.2703454e-05 |
| clipfrac           | 0.0           |
| explained_variance | -0.000113     |
| fps                | 120           |
| n_updates          | 1             |
| policy_entropy     | 8.958712      |
| policy_loss        | -0.0022244197 |
| serial_timesteps   | 128           |
| time_elapsed       | 3.34e-06      |
| total_timesteps    | 128           |
| value_loss         | 2278941.0     |
--------------------------------------
-------------------------------------
| approxkl           | 0.0003597149 |
| clipfrac           | 0.0          |
| explained_variance | 7.55e-05     |
| fps                | 150          |
| n_updates          | 2            |
| policy_entropy     | 8.957389     |
| policy_loss        | 0.0018449794 |
| serial_timesteps   | 256          |
| time_elapsed       | 1.06         |
| total_timesteps    | 256          |
| value_loss         | 767767.0     |
-------------------------------------
Traceback (most recent call last):
  File "train_agent_2.py", line 275, in <module>
    model.learn(total_timesteps=args.num_steps)# callback=callback)
  File "/home/iiitd/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 355, in learn
    update=timestep, cliprange_vf=cliprange_vf_now))
  File "/home/iiitd/.local/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 294, in _train_step
    writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
  File "/home/iiitd/.local/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 262, in add_run_metadata
    raise ValueError("The provided tag was already used for this event type")
ValueError: The provided tag was already used for this event type

**Comment by riz0410** [comment] 2020-10-09 06:18
@Miffyli 

It is working fine with full_tensorboard_log=False, so I am expecting some issue with the counter only.

**Comment by Miffyli** [comment] 2020-10-09 11:10
Sadly it is hard for me to debug this without a code to reproduce the error, and for me (and as you pointed out) the simple environments work as expected, and for some reason the environment you use raises the error. To get help please provide a minimal code to create the error (if you can not share your environment, then try to pinpoint the problem and share a minimal version of it that causes the bug).
