### ISSUE TITLE
Wrong episode_reward graph when using LSTM

### ISSUE THREAD

**Issue by pulver22** [hill-a/stable-baselines#224] opened 2019-03-07 17:06 UTC
**Describe the bug**
I started playing with LSTM with a custom CNN feature extractor. When I visualize the episode_reward plot in Tensorboard, if I use the `step` mode the result is as follow:
![image](https://user-images.githubusercontent.com/6864853/53974721-1aac9e00-40fb-11e9-800e-5653837384f8.png)

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: from source
 * GPU models and configuration: Nvidia 1080ti, NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0
 * Python version: 3.5
 * Tensorflow version: 1.12

**Comment by araffin** [comment] 2019-03-08 09:28
Hello,
could you provide a minimal code to reproduce?

I think this may be a duplicate of #143

**Comment by pulver22** [comment] 2019-03-08 10:07
Hi,

Thank you for coming back so quickly. I cannot offer you a reproducible example because I am working with my own environment built on top of `gym-gazebo`. But the main code is the following:

```
env = gym.make('GazeboThorvaldCameraEnv-v1'
env = DummyVecEnv([lambda : env])  # The algorithm require a vectorized environment to run

directory="/home/pulver/Desktop/test_clock/old/4/1/pre-normalised/multiplyer/LSTM"
ckp_path = directory + "4norm"

num_timesteps = 100000
test_episodes = 10

model = PPO2(NavigationCnnLstmPolicy, env=env, n_steps=800, nminibatches=1,  verbose=1, tensorboard_log=directory, full_tensorboard_log=True)

model.learn(total_timesteps=num_timesteps)
```

NB: NavigationCnnLstmPolicy is the standard LSTM with a custom CNN feature extractor.

**Comment by araffin** [comment] 2019-03-08 10:21
Ok, same problem with the same algorithm apparently. I will close this one to have only one issue on that.
Last question: what is your version of stable-baselines?

**Closed by araffin** 2019-03-08 10:21 UTC
Labels: more information needed

**Comment by pulver22** [comment] 2019-03-08 11:54
I had the latest version pushed in the repo, 2.4.1.
