### ISSUE TITLE
Training always restarts with very short episode lengths

### ISSUE THREAD

**Issue by pathway** [hill-a/stable-baselines#69] opened 2018-10-30 05:20 UTC
I noticed after training, reloading model, and then training again, the first few printouts of eplenmean are very low (in env where long episode corresponds to good performance).

For a long time, this made me suspect that training was being lost or destroyed, and I wondered if stable-baselines had a bug...

**Comment by pathway** [comment] 2018-10-30 05:21
After debug printing individual episode stats, I now think this this is simple due to this fact:

Very short episodes are the first to finish, thus are first to get included in stats, and so the first reported stats are artificially low.  

Not due to any bug but just as a side-effect of how the stats are being reported :)

**Comment by araffin** [comment] 2018-11-04 12:28
@pathway If you think this is not a bug, I let you close the issue ;)

**Closed** 2018-11-05 20:34 UTC
