### ISSUE TITLE
Wrong terminal state at the end of the episode (DDPG, TD3)

### ISSUE THREAD

**Issue by bl4ckrid3r** [hill-a/stable-baselines#769] opened 2020-03-26 12:46 UTC
After trying DDPG and TD3 on various environments, we find out that the terminal state at the end of the episode is overwritten by the state of the new starting episode. Was this done on purpose ? Will it affect the performance of the model ? or it's just a bug. 

![image](https://user-images.githubusercontent.com/19371416/77648260-20745c00-6f68-11ea-879e-7e3cfc5b4e4f.png)

P.S: The image represents the replay buffer of 'Pendulum-v0' from Gym.

**Comment by araffin** [comment] 2020-03-26 13:11
Duplicate of #400 (and it is in the doc)

**Closed** 2020-04-05 12:11 UTC
Labels: RTFM, duplicate, more information needed, question
