### ISSUE TITLE
Running custom env from the docker image

### ISSUE THREAD

**Issue by rracinskij** [hill-a/stable-baselines#632] opened 2019-12-26 06:13 UTC
Hi,

I'm trying to run a custom env from a docker image and encounter some problems with it (documentation suggests the use of RL model zoo, but it doesn't support custom envs):
1. `docker pull stablebaselines/stable-baselines` does not work, so the documentation probably should be updated to `docker pull stablebaselines/stable-baselines:v2.9.0`
2. then I run 
```
docker run -it --gpus=all --rm --network host --ipc=host \
  --mount src=$(pwd),target=/root/code/stable-baselines,type=bind stablebaselines/stable-baselines:v2.9.0 \
  bash -c "cd /root/code/stable-baselines/ && pip install stable-baselines[mpi] && /bin/bash"
```
and subsequently
`from stable_baselines.common.env_checker import check_env` in Python
but get an

> ImportError: No module named 'stable_baselines.common'
(same for any other stable_baselines module).

The system is an Ubuntu 16.04.6 LTS xenial with a GTX1080Ti and Docker 19.03.5.

**Comment by araffin** [comment] 2019-12-29 14:09
Hello,

Thanks for reporting the issue (we forgot to add the tag `latest` apparently). Did you try to use the cpu image too?

@AdamGleave related to this issue: I think there is a bug in the build script for the GPU image (the command line arguments are not passed properly, I get an error when running `USE_GPU=True ./scripts/build_docker.sh` because `$USE_GPU` is not defined in the dockerfile...

**Comment by AdamGleave** [comment] 2020-01-02 04:54
> Thanks for reporting the issue (we forgot to add the tag `latest` apparently). Did you try to use the cpu image too?

> @AdamGleave related to this issue: I think there is a bug in the build script for the GPU image (the command line arguments are not passed properly, I get an error when running `USE_GPU=True ./scripts/build_docker.sh` because `$USE_GPU` is not defined in the dockerfile...

Well caught. Both should be fixed in #640. I've modified the build script to automatically push the tag and latest if `RELEASE` is specified, and to pass USE_GPU through as `--build-arg`.

As for the rest of the issue, I'm not sure what the problem is. I can import `stable_baselines.common.env_checker` just fine when using `./scripts/run_docker_{cpu,gpu}.sh`. @rracinskij are you sure the issue is not with the code in `$(pwd)` that you're mounting in?

**Comment by rracinskij** [comment] 2020-01-06 19:54
@AdamGleave yes, the issue was in my code, sorry. However, I still get a `docker: Error response from daemon: Unknown runtime specified nvidia` error while using `--runtime=nvidia ` parameter in the `run_docker_gpu.sh` script. Changing it to `--gpus=all` works fine.

**Comment by AdamGleave** [comment] 2020-01-07 03:17
> @AdamGleave yes, the issue was with my code, sorry. However, I still get a `docker: Error response from daemon: Unknown runtime specified nvidia` error while using `--runtime=nvidia ` parameter in the `run_docker_gpu.sh` script. Changing it to `--gpus=all` works fine.

Good catch, think `--runtime nvidia` is only for NVidia Docker <2, `--gpus all` seems to be [the new way](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)). We should update the script.

**Comment by ChengYen-Tang** [comment] 2020-01-12 14:59
@rracinskij 
To make it easier for me to switch the stable-baselines version, I have build a docker image that can mounts stable-baselines project.
You can try it.

[ntutselab/stable-baselines-cpu](https://hub.docker.com/repository/docker/ntutselab/stable-baselines-cpu)
[ntutselab/stable-baselines-gpu](https://hub.docker.com/repository/docker/ntutselab/stable-baselines-gpu)

**Comment by araffin** [comment] 2020-01-12 19:51
Looks like #650 could solve that issue

@ChengYen-Tang we have the docker image of the zoo for that (cf doc), they were recently updated and are now under the `stablebaselines` domain (I will a PR for that)

**Comment by ChengYen-Tang** [comment] 2020-01-13 03:29
My image can quickly switch between versions and branches, without having to rebuild the image every time I update or modify some code.

Just mount the stable_baselines folder to / root / code / stable_baselines / in the container.
But every time I need to provide the local stable_baselines path to run the container.

**Comment by AdamGleave** [comment] 2020-01-14 03:39
> My image can quickly switch between versions and branches, without having to rebuild the image every time I update or modify some code.
> 
> Just mount the stable_baselines folder to / root / code / stable_baselines / in the container.
> But every time I need to provide the local stable_baselines path to run the container.

Could you explain why you can't achieve this with the official Stable Baselines image? Our `scripts/run_docker_{cpu,gpu}.sh` mount the working directory into `/root/code/stable-baselines`. Should be easy to modify the script to take a path to a Stable Baselines repository on the host machine if desired.

**Comment by AdamGleave** [comment] 2020-01-14 03:44
> @AdamGleave yes, the issue was with my code, sorry. However, I still get a `docker: Error response from daemon: Unknown runtime specified nvidia` error while using `--runtime=nvidia ` parameter in the `run_docker_gpu.sh` script. Changing it to `--gpus=all` works fine.

I think this should be fixed in https://github.com/hill-a/stable-baselines/pull/653 -- can you check the script works for you now?

**Comment by rracinskij** [comment] 2020-01-15 04:40
@AdamGleave, no, after downloading a new gpu image from Docker Hub and running it with the old script I still get the same `Unknown runtime specified nvidia.` error. Should I change the script?

**Comment by AdamGleave** [comment] 2020-01-15 22:10
> @AdamGleave, no, after downloading a new gpu image from Docker Hub and running it with the old script I still get the same `Unknown runtime specified nvidia.` error. Should I change the script?

I changed the script in #653

**Comment by rracinskij** [comment] 2020-01-17 18:43
Now everything works fine, thank you!

**Closed** 2020-01-17 19:34 UTC
Labels: bug, documentation
