### ISSUE TITLE
Model prediction gives all nan

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#331] opened 2019-05-20 08:18 UTC
n_cpu = 12
    env = PortfolioEnv(history=history, abbreviation=instruments, steps=settings['steps'], window_length=settings['window_length'])
    env = SubprocVecEnv([lambda: env for i in range(n_cpu)])

    print(settings['model_filename'])
    model = PPO2.load(settings['model_filename'])

    # intialized here
    obs = env.reset()
    states = model.initial_state  # get the initial state vector for the reccurent network
    dones = np.zeros(states.shape[0])  # set all environment to not done
    
    print(np.shape(obs))
    print(np.shape(states))
    print(np.shape(dones))
    
    print(obs)
    print(states)
    print(dones)

    # updated here
    # action, _values, states, _neglog = model.predict(obs, states, dones)
    action, _states = model.predict(obs, states, dones)

Gives:

(12, 120)
(12, 512)
(12,)

[[1.000000e+00 1.000000e+00 1.000000e+00 ... 1.057500e+05 1.061250e+05
  1.555900e+04]
 [1.000000e+00 1.000000e+00 1.000000e+00 ... 9.853750e+04 9.980000e+04
  4.457200e+04]
 [1.000000e+00 1.000000e+00 1.000000e+00 ... 1.042000e+05 1.044875e+05
  1.994300e+04]
 ...
 [1.000000e+00 1.000000e+00 1.000000e+00 ... 9.571250e+04 9.615000e+04
  2.808500e+04]
 [1.000000e+00 1.000000e+00 1.000000e+00 ... 9.853750e+04 9.980000e+04
  4.457200e+04]
 [1.000000e+00 1.000000e+00 1.000000e+00 ... 1.054250e+05 1.057750e+05
  1.149000e+04]]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

**Comment by araffin** [comment] 2019-05-20 08:39
Duplicate of #257 and #279

**Closed by araffin** 2019-05-20 08:39 UTC

**Comment by hn2** [comment] 2019-05-20 09:40
I still don't know how to solve this. Please advise.
